Object.assign(allLootTables, {

    "kattersstructures:chests/birch/armorer":       loot_village_armorer,
    "kattersstructures:chests/birch/cartographer":  loot_village_cartographer,
    "kattersstructures:chests/birch/fisherman":     loot_village_fisher,
    "kattersstructures:chests/birch/house":         loot_village_plains_house,
    "kattersstructures:chests/birch/leatherworker": loot_village_tannery,
    "kattersstructures:chests/birch/shepherd":      loot_village_shepherd,
    "kattersstructures:chests/birch/toolsmith":     loot_village_toolsmith,
    "kattersstructures:chests/birch/weaponsmith":   loot_village_weaponsmith,

    "kattersstructures:chests/cherry/armorer":      loot_village_armorer,
    "kattersstructures:chests/cherry/butcher":      loot_village_butcher,
    "kattersstructures:chests/cherry/cartographer": loot_village_cartographer,
    "kattersstructures:chests/cherry/cleric":        loot_village_temple,
    "kattersstructures:chests/cherry/fisherman":     loot_village_fisher,
    "kattersstructures:chests/cherry/fletcher":      loot_village_fletcher,
    "kattersstructures:chests/cherry/house":         loot_village_cherry_house,
    "kattersstructures:chests/cherry/leatherworker": loot_village_tannery,
    "kattersstructures:chests/cherry/mason":         loot_village_mason,
    // "kattersstructures:chests/cherry/pagode":        ???,
    "kattersstructures:chests/cherry/shepherd":      loot_village_shepherd,
    "kattersstructures:chests/cherry/toolsmith":     loot_village_toolsmith,
    "kattersstructures:chests/cherry/weaponsmith":   loot_village_weaponsmith,

    "kattersstructures:chests/armorer":      loot_village_armorer,
    "kattersstructures:chests/butcher":      loot_village_butcher,
    "kattersstructures:chests/cartographer": loot_village_cartographer,
    "kattersstructures:chests/cleric":        loot_village_temple,
    "kattersstructures:chests/fisherman":     loot_village_fisher,
    "kattersstructures:chests/fletcher":      loot_village_fletcher,
    "kattersstructures:chests/house":         loot_village_cherry_house,
    "kattersstructures:chests/leatherworker": loot_village_tannery,
    "kattersstructures:chests/mason":         loot_village_mason,
    // "kattersstructures:chests/pagode":        ???,
    "kattersstructures:chests/shepherd":      loot_village_shepherd,
    "kattersstructures:chests/toolsmith":     loot_village_toolsmith,
    "kattersstructures:chests/weaponsmith":   loot_village_weaponsmith,

    "kattersstructures:chests/jungle/armorer":       loot_village_armorer,
    "kattersstructures:chests/jungle/butcher":       loot_village_butcher,
    "kattersstructures:chests/jungle/cartographer":  loot_village_cartographer,
    "kattersstructures:chests/jungle/cleric":        loot_village_temple,
    // "kattersstructures:chests/jungle/disco":         loot_village_disco,
    "kattersstructures:chests/jungle/fisherman":     loot_village_fisher,
    "kattersstructures:chests/jungle/fletcher":      loot_village_fletcher,
    "kattersstructures:chests/jungle/house":         loot_village_jungle_house,
    "kattersstructures:chests/jungle/leatherworker": loot_village_tannery,
    "kattersstructures:chests/jungle/mason":         loot_village_mason,
    "kattersstructures:chests/jungle/shepherd":      loot_village_shepherd,
    "kattersstructures:chests/jungle/toolsmith":     loot_village_toolsmith,
    "kattersstructures:chests/jungle/weaponsmith":   loot_village_weaponsmith,

    "kattersstructures:chests/mesa/armorer":      loot_village_armorer,
    "kattersstructures:chests/mesa/cartographer": loot_village_cartographer,
    "kattersstructures:chests/mesa/farmer":         loot_village_badlands_house,
    "kattersstructures:chests/mesa/fisherman":     loot_village_fisher,
    "kattersstructures:chests/mesa/fletcher":      loot_village_fletcher,
    "kattersstructures:chests/mesa/house":         loot_village_badlands_house,
    "kattersstructures:chests/mesa/toolsmith":     loot_village_toolsmith,
    "kattersstructures:chests/mesa/weaponsmith":   loot_village_weaponsmith,
    //  "kattersstructures:chests/mesa/booze":         loot_village_mesa_house,
    //  "kattersstructures:chests/mesa/prison":        loot_village_mesa_house,
    //  "kattersstructures:chests/mesa/saloon":        loot_village_mesa_house,


    "kattersstructures:chests/ocean/armorer":       loot_village_armorer,
    "kattersstructures:chests/ocean/butcher":       loot_village_butcher,
    "kattersstructures:chests/ocean/cartographer":  loot_village_cartographer,
    "kattersstructures:chests/ocean/cleric":        loot_village_temple,
    "kattersstructures:chests/ocean/fletcher":      loot_village_fletcher,
    "kattersstructures:chests/ocean/house":         loot_village_ocean_house,
    "kattersstructures:chests/ocean/leatherworker": loot_village_tannery,
    "kattersstructures:chests/ocean/lighthouse":    loot_lighthouse,
    "kattersstructures:chests/ocean/mason":         loot_village_mason,
    "kattersstructures:chests/ocean/random":        loot_kattersstructures_ocean_random,
    "kattersstructures:chests/ocean/shepherd":      loot_village_shepherd,
    "kattersstructures:chests/ocean/toolsmith":     loot_village_toolsmith,
    "kattersstructures:chests/ocean/weaponsmith":   loot_village_weaponsmith,

    "kattersstructures:chests/swamp/armorer":      loot_village_armorer,
    // "kattersstructures:chests/swamp/big_stem":     loot_big_stem,
    "kattersstructures:chests/swamp/butcher":      loot_village_butcher,
    "kattersstructures:chests/swamp/cartographer": loot_village_cartographer,
    "kattersstructures:chests/swamp/cleric":       loot_village_temple,
    "kattersstructures:chests/swamp/fisherman":    loot_village_fisher,
    "kattersstructures:chests/swamp/fletcher":     loot_village_fletcher,
    // "kattersstructures:chests/swamp/grave":        loot_grave,
    "kattersstructures:chests/swamp/house":        loot_village_swamp_house,
    "kattersstructures:chests/swamp/leatherworker": loot_village_tannery,
    "kattersstructures:chests/swamp/lighthouse":   loot_lighthouse,
    "kattersstructures:chests/swamp/mason":        loot_village_mason,
    "kattersstructures:chests/swamp/shepherd":     loot_village_shepherd,
    "kattersstructures:chests/swamp/toolsmith":    loot_village_toolsmith,
    "kattersstructures:chests/swamp/weaponsmith":  loot_village_weaponsmith,

    "kattersstructures:chests/underground/armorer":      loot_village_armorer,
    "kattersstructures:chests/underground/cleric":        loot_village_temple,
    "kattersstructures:chests/underground/fletcher":      loot_village_fletcher,
    "kattersstructures:chests/underground/house":         loot_village_underground_house,
    "kattersstructures:chests/underground/leatherworker": loot_village_tannery,
    "kattersstructures:chests/underground/mason":         loot_village_mason,
    "kattersstructures:chests/underground/random":        loot_kattersstructures_underground_random,
    "kattersstructures:chests/underground/toolsmith":     loot_village_toolsmith,
    "kattersstructures:chests/underground/treasures":     loot_village_treasure,
    "kattersstructures:chests/underground/weaponsmith":   loot_village_weaponsmith,

    "kattersstructures:chests/windmill/windmill":   loot_village_farm,

})