const minecraftLootTable = {
    "minecraft:chests/abandoned_mineshaft":             loot_abandoned_mineshaft,
    // "minecraft:chests/ancient_city":                 loot_ancient_city,
    // "minecraft:chests/ancient_city_ice_box":         loot_ancient_city_ice_box,
    // "minecraft:chests/bastion_bridge":               loot_bastion_bridge,
    // "minecraft:chests/bastion_hoglin_stable":        loot_bastion_hoglin_stable,
    // "minecraft:chests/bastion_other":                loot_bastion_other,
    // "minecraft:chests/bastion_treasure":             loot_bastion_treasure,
    "minecraft:chests/buried_treasure":                 loot_buried_treasure,
    "minecraft:chests/desert_pyramid":                  loot_desert_pyramid,
    // "minecraft:chests/end_city_treasure":            loot_end_city_treasure,
    "minecraft:chests/igloo_chest":                     loot_igloo,
    "minecraft:chests/jungle_temple":                   loot_jungle_temple,
    // "minecraft:chests/jungle_temple_dispenser":      loot_jungle_temple_dispenser,
    // "minecraft:chests/nether_bridge":                loot_nether_bridge,
    "minecraft:chests/pillager_outpost":                loot_pillager_outpost,
    "minecraft:chests/ruined_portal":                   loot_ruined_portal,
    "minecraft:chests/shipwreck_map":                   { mode: "ADD", data: loot_shipwreck_map },    
    "minecraft:chests/shipwreck_supply":                loot_shipwreck_supply,
    "minecraft:chests/shipwreck_treasure":              loot_shipwreck_treasure,
    "minecraft:chests/simple_dungeon":                  loot_simple_dungeon,
    // "minecraft:chests/spawn_bonus_chest":            loot_spawn_bonus_chest,
    "minecraft:chests/stronghold_corridor":             loot_stronghold_corridor,
    "minecraft:chests/stronghold_crossing":             loot_stronghold_supply,
    "minecraft:chests/stronghold_library":              loot_stronghold_library,
    "minecraft:chests/underwater_ruin_big":             { mode: "ADD", data: loot_underwater_ruin_big },
    "minecraft:chests/underwater_ruin_small":           { mode: "ADD", data: loot_underwater_ruin_small },
    "minecraft:chests/woodland_mansion":                loot_woodland_mansion,

    "minecraft:chests/village/village_armorer":        loot_village_armorer,
    "minecraft:chests/village/village_butcher":        loot_village_butcher,
    "minecraft:chests/village/village_cartographer":   loot_village_cartographer,
    "minecraft:chests/village/village_desert_house":   loot_village_desert_house,
    "minecraft:chests/village/village_fisher":         loot_village_fisher,
    "minecraft:chests/village/village_fletcher":       loot_village_fletcher,
    "minecraft:chests/village/village_mason":          loot_village_mason,
    "minecraft:chests/village/village_plains_house":   loot_village_plains_house,
    "minecraft:chests/village/village_savanna_house":  loot_village_savanna_house,
    "minecraft:chests/village/village_shepherd":       loot_village_shepherd,
    "minecraft:chests/village/village_snowy_house":    loot_village_snowy_house,
    "minecraft:chests/village/village_taiga_house":    loot_village_taiga_house,
    "minecraft:chests/village/village_tannery":        loot_village_tannery,
    "minecraft:chests/village/village_temple":         loot_village_temple,
    "minecraft:chests/village/village_toolsmith":      loot_village_toolsmith,
    "minecraft:chests/village/village_weaponsmith":    loot_village_weaponsmith,

    // "minecraft:chests/trial_chambers/corridor":                loot_trial_chambers_corridor,
    // "minecraft:chests/trial_chambers/entrance":                loot_trial_chambers_entrance,
    // "minecraft:chests/trial_chambers/intersection":            loot_trial_chambers_intersection,
    // "minecraft:chests/trial_chambers/intersection_barrel":     loot_trial_chambers_intersection_barrel,
    // "minecraft:chests/trial_chambers/reward":                  loot_trial_chambers_reward,
    // "minecraft:chests/trial_chambers/reward_common":           loot_trial_chambers_reward_common,
    // "minecraft:chests/trial_chambers/reward_ominous":          loot_trial_chambers_reward_ominous,
    // "minecraft:chests/trial_chambers/reward_ominous_common":   loot_trial_chambers_reward_ominous_common,
    // "minecraft:chests/trial_chambers/reward_ominous_rare":     loot_trial_chambers_reward_ominous_rare,
    // "minecraft:chests/trial_chambers/reward_ominous_unique":   loot_trial_chambers_reward_ominous_unique,
    // "minecraft:chests/trial_chambers/reward_rare":             loot_trial_chambers_reward_rare,
    // "minecraft:chests/trial_chambers/reward_unique":           loot_trial_chambers_reward_unique,
    // "minecraft:chests/trial_chambers/supply":                  loot_trial_chambers_supply,
}

registerLootTables(minecraftLootTable);