Object.assign(allLootTables, {
    // "repurposed_structures:chests/lucky_pool":                                loot_lucky_pool,

    // "repurposed_structures:chests/ancient_cities/end":                        loot_ancient_cities_end,
    // "repurposed_structures:chests/ancient_cities/end_spawner_box":            loot_ancient_cities_end_spawner_box,
    // "repurposed_structures:chests/ancient_cities/nether":                     loot_ancient_cities_nether,
    // "repurposed_structures:chests/ancient_cities/nether_magma_box":           loot_ancient_cities_nether_magma_box,
    // "repurposed_structures:chests/ancient_cities/ocean":                      loot_ancient_cities_ocean,
    // "repurposed_structures:chests/ancient_cities/ocean_ice_box":              loot_ancient_cities_ocean_ice_box,

    // "repurposed_structures:chests/cities/nether":                             loot_cities_nether,
    // "repurposed_structures:chests/cities/overworld":                          loot_cities_overworld,

    "repurposed_structures:chests/dungeons/badlands":                         loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/dark_forest":                      loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/deep":                             loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/desert":                           loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/icy":                              loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/jungle":                           loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/mushroom":                         loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/nether":                           loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/ocean":                            loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/snow":                             loot_simple_dungeon,
    "repurposed_structures:chests/dungeons/swamp":                            loot_simple_dungeon,

    // "repurposed_structures:chests/fortresses/jungle_center":                  loot_fortresses_jungle_center,
    // "repurposed_structures:chests/fortresses/jungle_hallway":                 loot_fortresses_jungle_hallway,
    // "repurposed_structures:chests/fortresses/jungle_shrine":                  loot_fortresses_jungle_shrine,

    "repurposed_structures:chests/igloos/grassy":                             loot_igloo,
    "repurposed_structures:chests/igloos/mangrove":                           loot_igloo,
    "repurposed_structures:chests/igloos/mushroom":                           loot_igloo,
    "repurposed_structures:chests/igloos/stone":                              loot_igloo,

    "repurposed_structures:chests/mansions/birch":                            loot_woodland_mansion,
    "repurposed_structures:chests/mansions/birch_storage":                    loot_woodland_mansion,
    "repurposed_structures:chests/mansions/desert":                           loot_woodland_mansion,
    "repurposed_structures:chests/mansions/desert_storage":                   loot_woodland_mansion,
    "repurposed_structures:chests/mansions/jungle":                           loot_woodland_mansion,
    "repurposed_structures:chests/mansions/jungle_storage":                   loot_woodland_mansion,
    "repurposed_structures:chests/mansions/mangrove":                         loot_woodland_mansion,
    "repurposed_structures:chests/mansions/mangrove_storage":                 loot_woodland_mansion,
    "repurposed_structures:chests/mansions/oak":                              loot_woodland_mansion,
    "repurposed_structures:chests/mansions/oak_storage":                      loot_woodland_mansion,
    "repurposed_structures:chests/mansions/savanna":                          loot_woodland_mansion,
    "repurposed_structures:chests/mansions/savanna_storage":                  loot_woodland_mansion,
    "repurposed_structures:chests/mansions/snowy":                            loot_woodland_mansion,
    "repurposed_structures:chests/mansions/snowy_storage":                    loot_woodland_mansion,
    "repurposed_structures:chests/mansions/taiga":                            loot_woodland_mansion,
    "repurposed_structures:chests/mansions/taiga_storage":                    loot_woodland_mansion,

    "repurposed_structures:chests/mineshafts/birch":                          loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/crimson":                        loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/dark_forest":                    loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/desert":                         loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/end":                            loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/icy":                            loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/jungle":                         loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/nether":                         loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/ocean":                          loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/savanna":                        loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/stone":                          loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/swamp":                          loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/taiga":                          loot_abandoned_mineshaft,
    "repurposed_structures:chests/mineshafts/warped":                         loot_abandoned_mineshaft,

    "repurposed_structures:chests/monuments/desert":                          loot_buried_treasure,
    "repurposed_structures:chests/monuments/icy":                             loot_buried_treasure,
    "repurposed_structures:chests/monuments/jungle":                          loot_buried_treasure,
    "repurposed_structures:chests/monuments/nether":                          loot_buried_treasure,

    "repurposed_structures:chests/outposts/badlands":                         loot_pillager_outpost,
    "repurposed_structures:chests/outposts/birch":                            loot_pillager_outpost,
    "repurposed_structures:chests/outposts/crimson":                          loot_pillager_outpost,
    "repurposed_structures:chests/outposts/desert":                           loot_pillager_outpost,
    "repurposed_structures:chests/outposts/giant_tree_taiga":                 loot_pillager_outpost,
    "repurposed_structures:chests/outposts/icy":                              loot_pillager_outpost,
    "repurposed_structures:chests/outposts/jungle":                           loot_pillager_outpost,
    "repurposed_structures:chests/outposts/mangrove":                         loot_pillager_outpost,
    "repurposed_structures:chests/outposts/nether_brick":                     loot_pillager_outpost,
    "repurposed_structures:chests/outposts/oak":                              loot_pillager_outpost,
    "repurposed_structures:chests/outposts/snowy":                            loot_pillager_outpost,
    "repurposed_structures:chests/outposts/taiga":                            loot_pillager_outpost,
    "repurposed_structures:chests/outposts/warped":                           loot_pillager_outpost,

    "repurposed_structures:chests/pyramids/dark_forest":                      loot_desert_pyramid,
    "repurposed_structures:chests/pyramids/end":                              loot_desert_pyramid,
    "repurposed_structures:chests/pyramids/flower_forest":                    loot_desert_pyramid,
    "repurposed_structures:chests/pyramids/giant_tree_taiga":                 loot_desert_pyramid,
    "repurposed_structures:chests/pyramids/icy":                              loot_desert_pyramid,
    "repurposed_structures:chests/pyramids/jungle":                           loot_desert_pyramid,
    "repurposed_structures:chests/pyramids/mushroom":                         loot_desert_pyramid,
    "repurposed_structures:chests/pyramids/snowy":                            loot_desert_pyramid,

    // "repurposed_structures:chests/ruins/nether":                              loot_ruins_nether,

    // "repurposed_structures:chests/strongholds/nether_hallway":                loot_stronghold_corridor,
    // "repurposed_structures:chests/strongholds/nether_library":                loot_stronghold_library,
    // "repurposed_structures:chests/strongholds/nether_storage_room":           loot_stronghold_supply,

    "repurposed_structures:chests/temples/basalt":                            loot_jungle_temple,
    "repurposed_structures:chests/temples/crimson":                           loot_jungle_temple,
    "repurposed_structures:chests/temples/ocean":                             loot_jungle_temple,
    "repurposed_structures:chests/temples/soul":                              loot_jungle_temple,
    "repurposed_structures:chests/temples/taiga":                             loot_jungle_temple,
    "repurposed_structures:chests/temples/warped":                            loot_jungle_temple,
    "repurposed_structures:chests/temples/wasteland":                         loot_jungle_temple,

    "repurposed_structures:chests/villages/badlands_house":                   loot_village_badlands_house,
    "repurposed_structures:chests/villages/bamboo_house":                     loot_village_jungle_house,
    "repurposed_structures:chests/villages/birch_house":                      loot_village_plains_house,
    "repurposed_structures:chests/villages/cherry_house":                     loot_village_cherry_house,
    // "repurposed_structures:chests/villages/crimson_cartographer":             loot_village_cartographer,
    // "repurposed_structures:chests/villages/crimson_fisher":                   loot_village_fisher,
    // "repurposed_structures:chests/villages/crimson_house":                    loot_village_crimson_house,
    // "repurposed_structures:chests/villages/crimson_tannery":                  loot_village_tannery,
    // "repurposed_structures:chests/villages/crimson_weaponsmith":              loot_village_weaponsmith,
    "repurposed_structures:chests/villages/dark_forest_house":                loot_village_dark_forest_house,
    "repurposed_structures:chests/villages/giant_taiga_house":                loot_village_taiga_house,
    "repurposed_structures:chests/villages/jungle_house":                     loot_village_jungle_house,
    "repurposed_structures:chests/villages/mountains_house":                  loot_village_snowy_house,
    "repurposed_structures:chests/villages/mushroom_house":                   loot_village_mushroom_house,
    "repurposed_structures:chests/villages/oak_house":                        loot_village_plains_house,
    "repurposed_structures:chests/villages/ocean_cartographer":               loot_village_cartographer,
    "repurposed_structures:chests/villages/ocean_house":                      loot_village_ocean_house,
    "repurposed_structures:chests/villages/swamp_house":                      loot_village_swamp_house,
    // "repurposed_structures:chests/villages/warped_cartographer":              loot_village_cartographer,
    // "repurposed_structures:chests/villages/warped_fisher":                    loot_village_fisher,
    // "repurposed_structures:chests/villages/warped_house":                     loot_village_plains_house,
    // "repurposed_structures:chests/villages/warped_tannery":                   loot_village_tannery,
    // "repurposed_structures:chests/villages/warped_weaponsmith":               loot_village_weaponsmith,

    // "repurposed_structures:chests/bastions/underground/bridge":               loot_bastions_underground_bridge,
    // "repurposed_structures:chests/bastions/underground/other":                loot_bastions_underground_other,
    // "repurposed_structures:chests/bastions/underground/skeleton_horse_stable": loot_bastions_underground_skeleton_horse_stable,
    // "repurposed_structures:chests/bastions/underground/treasure":             loot_bastions_underground_treasure,

    // "repurposed_structures:chests/ruined_portals/end/large_portal":            loot_ruined_portal,
    // "repurposed_structures:chests/ruined_portals/end/small_portal":            loot_ruined_portal,

    // "repurposed_structures:chests/ruins/land_cold/large":                      { mode: "ADD", data: loot_underwater_ruin_big },
    // "repurposed_structures:chests/ruins/land_cold/small":                      { mode: "ADD", data: loot_underwater_ruin_small },
    // "repurposed_structures:chests/ruins/land_hot/large":                       { mode: "ADD", data: loot_underwater_ruin_big },
    // "repurposed_structures:chests/ruins/land_hot/small":                       { mode: "ADD", data: loot_underwater_ruin_small },
    // "repurposed_structures:chests/ruins/land_icy/large":                       { mode: "ADD", data: loot_underwater_ruin_big },
    // "repurposed_structures:chests/ruins/land_icy/small":                       { mode: "ADD", data: loot_underwater_ruin_small },
    // "repurposed_structures:chests/ruins/land_warm/large":                      { mode: "ADD", data: loot_underwater_ruin_big },
    // "repurposed_structures:chests/ruins/land_warm/small":                      { mode: "ADD", data: loot_underwater_ruin_small },

    // "repurposed_structures:chests/shipwrecks/crimson/map":                     { mode: "ADD", data: loot_shipwreck_map },
    // "repurposed_structures:chests/shipwrecks/crimson/supply":                  loot_shipwreck_supply,
    // "repurposed_structures:chests/shipwrecks/crimson/treasure":               loot_shipwreck_treasure,
    // "repurposed_structures:chests/shipwrecks/end/map":                        { mode: "ADD", data: loot_shipwreck_map },
    // "repurposed_structures:chests/shipwrecks/end/supply":                     loot_shipwreck_supply,
    // "repurposed_structures:chests/shipwrecks/end/treasure":                  loot_shipwreck_treasure,
    // "repurposed_structures:chests/shipwrecks/nether_bricks/treasure":          loot_shipwreck_treasure,
    // "repurposed_structures:chests/shipwrecks/warped/map":                     { mode: "ADD", data: loot_shipwreck_map },
    // "repurposed_structures:chests/shipwrecks/warped/supply":                  loot_shipwreck_supply,
    // "repurposed_structures:chests/shipwrecks/warped/treasure":                 loot_shipwreck_treasure,

    
})