const tableToClear = [

        "brewery:chests/pillager_outpost",
        "brewery:chests/woodland_mansion",
        "brewery:chests/village/village_desert_house",
        "brewery:chests/village/village_plains_house",
        "brewery:chests/village/village_savanna_house",
        "brewery:chests/village/village_taiga_house",

        "chalk:chests/village_chalks",
        "chalk:chests/abandoned_mineshaft_chalks",
        "chalk:chests/desert_pyramid_chalks",
        "chalk:chests/simple_dungeon_chalks",

        "dumplings_delight:chests/ed_abandoned_mineshaft",
        "dumplings_delight:chests/ed_pillager_outpost",
        "dumplings_delight:chests/ed_shipwreck_supply",
        "dumplings_delight:chests/ed_simple_dungeon",
        "dumplings_delight:chests/ed_village_desert_house",
        "dumplings_delight:chests/ed_village_plains_house",
        "dumplings_delight:chests/ed_village_savanna_house",
        "dumplings_delight:chests/ed_village_snowy_house",
        "dumplings_delight:chests/ed_village_taiga_house",

        "farmersdelight:chests/fd_abandoned_mineshaft",
        // "farmersdelight:chests/fd_bastion_hoglin_stable",
        // "farmersdelight:chests/fd_bastion_treasure",
        "farmersdelight:chests/fd_end_city_treasure",
        "farmersdelight:chests/fd_pillager_outpost",
        "farmersdelight:chests/fd_ruined_portal",
        "farmersdelight:chests/fd_shipwreck_supply",
        "farmersdelight:chests/fd_simple_dungeon",
        "farmersdelight:chests/fd_village_butcher",
        "farmersdelight:chests/fd_village_desert_house",
        "farmersdelight:chests/fd_village_plains_house",
        "farmersdelight:chests/fd_village_savanna_house",
        "farmersdelight:chests/fd_village_snowy_house",
        "farmersdelight:chests/fd_village_taiga_house",

        "rationcraft:chests/abandoned_mineshaft",
        "rationcraft:chests/igloo_chest",
        "rationcraft:chests/stronghold_crossing",
        "rationcraft:chests/village/village_butcher",
        "rationcraft:chests/village/village_fisher",

        "vanillacookbook:chests/nether",
        "vanillacookbook:chests/simple_dungeon",
        "vanillacookbook:chests/spawn_bonus_chest",
        "vanillacookbook:chests/village_desert_house",
        "vanillacookbook:chests/village_plains_house",
        "vanillacookbook:chests/village_savanna_house",
        "vanillacookbook:chests/village_snowy_house",
        "vanillacookbook:chests/village_taiga_house",
        "vanillacookbook:chests/woodland_mansion",
        "vanillacookbook:chests/abandoned_mineshaft",
        "vanillacookbook:chests/bastion_treasure",
        "vanillacookbook:chests/end_city_treasure",
        "vanillacookbook:chests/bonus_chest",
        "vanillacookbook:chests/end_city",
        "vanillacookbook:chests/village_desert",
        "vanillacookbook:chests/village_plains",
        "vanillacookbook:chests/village_savanna",
        "vanillacookbook:chests/village_snowy",
        "vanillacookbook:chests/village_taiga",

        "supplementaries:inject/dungeon_blue_bomb",
        "supplementaries:inject/dungeon_flax",
        "supplementaries:inject/dungeon_quiver",
        "supplementaries:inject/end_city_stasis",
        "supplementaries:inject/fishing_treasure_antique_ink",
        "supplementaries:inject/fortress_blue_bomb",
        "supplementaries:inject/fortress_bomb",
        "supplementaries:inject/mansion_quiver",
        "supplementaries:inject/mineshaft_blue_bomb",
        "supplementaries:inject/mineshaft_bomb",
        "supplementaries:inject/mineshaft_flax",
        "supplementaries:inject/mineshaft_rope",
        "supplementaries:inject/pillager_flax",
        "supplementaries:inject/shipwreck_storage_flax",
        "supplementaries:inject/shipwreck_treasure_globe",
        "supplementaries:inject/stronghold_blue_bomb",
        "supplementaries:inject/stronghold_bomb",
        "supplementaries:inject/temple_blue_bomb",
        "supplementaries:inject/temple_bomb",
        "supplementaries:inject/temple_spikes",
        "supplementaries:inject/test",

        "touhou_little_maid:chest/structure_spawn_maid_gift",

        "corn_delight:village_house",
        "corn_delight:shipwreck_supply",


        // "sawmill:chests/village_carpenter_desert",
        // "sawmill:chests/village_carpenter_plains",
        // "sawmill:chests/village_carpenter_taiga",
    ];

clearLootTable(tableToClear);