// ==================== 1. 配置数组 ====================
let DUPLICATE_ITEMS_CONFIG = [

    // === 1. 蔬菜类 (Vegetables) ===
    { result: "lootjs:beetroot",            candidates: ["minecraft:beetroot"] },
    { result: "lootjs:beetroot_seeds",      candidates: ["minecraft:beetroot_seeds"] },
    { result: "lootjs:bell_pepper_green",   candidates: ["rusticdelight:bell_pepper_green"] },
    { result: "lootjs:bell_pepper_red",     candidates: ["rusticdelight:bell_pepper_red"] },
    { result: "lootjs:bell_pepper_yellow",  candidates: ["rusticdelight:bell_pepper_yellow"] },
    { result: "lootjs:cabbage",             candidates: ["farmersdelight:cabbage"] },
    { result: "lootjs:cabbage_seeds",       candidates: ["farmersdelight:cabbage_seeds"] },
    { result: "lootjs:carrot",              candidates: ["minecraft:carrot"] },
    { result: "lootjs:chinese_cabbage",     candidates: ["dumplings_delight:chinese_cabbage"] },
    { result: "lootjs:chinese_cabbage_seeds", candidates: ["dumplings_delight:chinese_cabbage_seeds"] },
    { result: "lootjs:corn",                candidates: ["farm_and_charm:corn", "corn_delight:corn", "culturaldelights:corn_cob"] },
    { result: "lootjs:corn_seeds",          candidates: ["farm_and_charm:kernels", "corn_delight:corn_seeds", "culturaldelights:corn_kernels"] },    
    { result: "lootjs:cucumber",            candidates: ["youkaisfeasts:cucumber", "youkaishomecoming:cucumber", "vintagedelight:cucumber", "culturaldelights:cucumber"] },
    { result: "lootjs:cucumber_seeds",      candidates: ["youkaisfeasts:cucumber_seeds", "youkaishomecoming:cucumber_seeds", "vintagedelight:cucumber_seeds", "culturaldelights:cucumber_seeds"] },
    { result: "lootjs:eggplant",            candidates: ["dumplings_delight:eggplant", "culturaldelights:eggplant"] },
    { result: "lootjs:eggplant_seeds",      candidates: ["dumplings_delight:eggplant_seeds", "culturaldelights:eggplant_seeds"] },
    { result: "lootjs:fennel",              candidates: ["dumplings_delight:fennel"] },
    { result: "lootjs:fennel_seeds",        candidates: ["dumplings_delight:fennel_seeds"] },
    { result: "lootjs:garlic",              candidates: ["dumplings_delight:garlic"] },
    { result: "lootjs:garlic_clove",        candidates: ["dumplings_delight:garlic_clove"] },
    { result: "lootjs:garlic_chive",        candidates: ["dumplings_delight:garlic_chive"] },
    { result: "lootjs:greenonion",          candidates: ["dumplings_delight:greenonion"] },
    { result: "lootjs:hops",                candidates: ["brewery:hops"] },
    { result: "lootjs:kelp",                candidates: ["minecraft:kelp"] },
    { result: "lootjs:lettuce",             candidates: ["kaleidoscope_cookery:lettuce", "farm_and_charm:lettuce"] },
    { result: "lootjs:lettuce_seeds",       candidates: ["kaleidoscope_cookery:lettuce_seed", "farm_and_charm:lettuce_seeds"] },
    { result: "lootjs:brown_mushroom",      candidates: ["minecraft:brown_mushroom"] },
    { result: "lootjs:red_mushroom",        candidates: ["minecraft:red_mushroom"] },
    { result: "lootjs:onion",               candidates: ["farmersdelight:onion", "farm_and_charm:onion"] },
    { result: "lootjs:pepper",              candidates: ["kaleidoscope_cookery:red_chili", /* "kaleidoscope_cookery:green_chili",  */"muffins_thaidelight:pepper", "vintagedelight:ghost_pepper", "casualnessdelight:capsicum"] },
    { result: "lootjs:pepper_seeds",        candidates: ["kaleidoscope_cookery:chili_seed", "muffins_thaidelight:pepper_seeds", "vintagedelight:ghost_pepper_seeds", "casualnessdelight:capsicum_seeds"] },
    { result: "lootjs:pickle",              candidates: ["vintagedelight:pickle", "culturaldelights:pickle"] },
    { result: "lootjs:poisonous_potato",    candidates: ["minecraft:poisonous_potato"] },
    { result: "lootjs:potato",              candidates: ["minecraft:potato"] },
    { result: "lootjs:pumpkin",             candidates: ["minecraft:pumpkin"] },
    { result: "lootjs:pumpkin_slice",       candidates: ["farmersdelight:pumpkin_slice"] },
    { result: "lootjs:pumpkin_seeds",       candidates: ["minecraft:pumpkin_seeds"] },
    { result: "lootjs:rotten_tomato",       candidates: ["farmersdelight:rotten_tomato", "farm_and_charm:rotten_tomato"] },
    { result: "lootjs:tomato",              candidates: ["kaleidoscope_cookery:tomato", "farmersdelight:tomato", "farm_and_charm:tomato", "bakeries:tomato"] },
    { result: "lootjs:tomato_seeds",        candidates: ["kaleidoscope_cookery:tomato_seed", "farmersdelight:tomato_seeds", "farm_and_charm:tomato_seeds"] },
    { result: "lootjs:white_eggplant",      candidates: ["culturaldelights:white_eggplant"] },

    // === 2. 水果类 (Fruits & Berries) ===
    { result: "lootjs:apple",               candidates: ["minecraft:apple"] },
    { result: "lootjs:apple_sapling",       candidates: ["fruitsdelight:apple_sapling"] },
    { result: "lootjs:avocado",             candidates: ["culturaldelights:avocado"] },
    { result: "lootjs:avocado_sapling",     candidates: ["culturaldelights:avocado_sapling"] },
    { result: "lootjs:bayberry",            candidates: ["fruitsdelight:bayberry"] },
    { result: "lootjs:bayberry_sapling",    candidates: ["fruitsdelight:bayberry_sapling"] },
    { result: "lootjs:berry",               candidates: ["minecraft:sweet_berries"] },
    { result: "lootjs:black_grape",         candidates: ["youkaishomecoming:black_grape", "youkaisfeasts:black_grape"] },
    { result: "lootjs:black_grape_seeds",   candidates: ["youkaishomecoming:black_grape_seeds", "youkaisfeasts:black_grape_seeds"] },
    { result: "lootjs:blueberry",           candidates: ["fruitsdelight:blueberry"] },
    { result: "lootjs:cherry",              candidates: ["seeddelight:cherry"] },
    { result: "lootjs:cranberry",           candidates: ["fruitsdelight:cranberry"] },
    { result: "lootjs:durian_sapling",      candidates: ["fruitsdelight:durian_sapling"] },
    { result: "lootjs:durian_flesh",        candidates: ["fruitsdelight:durian_flesh"] },
    { result: "lootjs:durian",              candidates: ["fruitsdelight:durian"] },
    { result: "lootjs:fig",                 candidates: ["fruitsdelight:fig"] },
    { result: "lootjs:fig_sapling",         candidates: ["fruitsdelight:fig_sapling"] },
    { result: "lootjs:gearo_berry",         candidates: ["vintagedelight:gearo_berry"] },
    { result: "lootjs:glowberry",           candidates: ["minecraft:glow_berries"] },
    { result: "lootjs:hamimelon",           candidates: ["fruitsdelight:hamimelon"] },
    { result: "lootjs:hamimelon_slice",     candidates: ["fruitsdelight:hamimelon_slice"] },
    { result: "lootjs:hamimelon_seeds",     candidates: ["fruitsdelight:hamimelon_seeds"] },
    { result: "lootjs:hawberry",            candidates: ["fruitsdelight:hawberry"] },
    { result: "lootjs:hawberry_sapling",    candidates: ["fruitsdelight:hawberry_sapling"] },
    { result: "lootjs:kiwi",                candidates: ["fruitsdelight:kiwi"] },
    { result: "lootjs:kiwi_sapling",        candidates: ["fruitsdelight:kiwi_sapling"] },
    { result: "lootjs:lemon",               candidates: ["fruitsdelight:lemon"] },
    { result: "lootjs:lemon_seeds",         candidates: ["fruitsdelight:lemon_seeds"] },
    { result: "lootjs:lime",                candidates: ["muffins_thaidelight:lime"] },
    { result: "lootjs:lime_sapling",        candidates: ["muffins_thaidelight:lime_sapling"] },
    { result: "lootjs:lychee",              candidates: ["fruitsdelight:lychee"] },
    { result: "lootjs:lychee_sapling",      candidates: ["fruitsdelight:lychee_sapling"] },
    { result: "lootjs:mango",               candidates: ["fruitsdelight:mango"] },
    { result: "lootjs:mango_sapling",       candidates: ["fruitsdelight:mango_sapling"] },
    { result: "lootjs:mangosteen",          candidates: ["fruitsdelight:mangosteen"] },
    { result: "lootjs:mangosteen_sapling",  candidates: ["fruitsdelight:mangosteen_sapling"] },
    { result: "lootjs:melon",               candidates: ["minecraft:melon"] },
    { result: "lootjs:melon_slice",         candidates: ["minecraft:melon_slice"] },
    { result: "lootjs:melon_seeds",         candidates: ["minecraft:melon_seeds"] },
    { result: "lootjs:orange",              candidates: ["fruitsdelight:orange"] },
    { result: "lootjs:orange_sapling",      candidates: ["fruitsdelight:orange_sapling"] },
    { result: "lootjs:papaya",              candidates: ["muffins_thaidelight:papaya"] },
    { result: "lootjs:peach",               candidates: ["fruitsdelight:peach"] },
    { result: "lootjs:peach_sapling",       candidates: ["fruitsdelight:peach_sapling"] },
    { result: "lootjs:pear",                candidates: ["fruitsdelight:pear"] },
    { result: "lootjs:pear_sapling",        candidates: ["fruitsdelight:pear_sapling"] },
    { result: "lootjs:persimmon",           candidates: ["fruitsdelight:persimmon"] },
    { result: "lootjs:persimmon_sapling",   candidates: ["fruitsdelight:persimmon_sapling"] },
    { result: "lootjs:pineapple",           candidates: ["fruitsdelight:pineapple", "pineapple_delight:pineapple"] },
    { result: "lootjs:pineapple_slice",     candidates: ["fruitsdelight:pineapple_slice", "pineapple_delight:pineapple_slice"] },
    { result: "lootjs:pineapple_sapling",   candidates: ["fruitsdelight:pineapple_sapling", "pineapple_delight:pineapple_crop"] },
    { result: "lootjs:red_grape",           candidates: ["youkaishomecoming:red_grape", "youkaisfeasts:red_grape"] },
    { result: "lootjs:red_grape_seeds",     candidates: ["youkaishomecoming:red_grape_seeds", "youkaisfeasts:red_grape_seeds"] },
    { result: "lootjs:rosehip",             candidates: ["seeddelight:rosehip"] },
    { result: "lootjs:strawberry",          candidates: ["farm_and_charm:strawberry"] },
    { result: "lootjs:strawberry_seeds",    candidates: ["farm_and_charm:strawberry_seeds"] },
    { result: "lootjs:sweetberry",          candidates: ["minecraft:sweet_berries"] },
    { result: "lootjs:sweetberry_pips",     candidates: ["berry_good:sweet_berry_pips"] },
    { result: "lootjs:white_grape",         candidates: ["youkaishomecoming:white_grape", "youkaisfeasts:white_grape"] },
    { result: "lootjs:white_grape_seeds",   candidates: ["youkaishomecoming:white_grape_seeds", "youkaisfeasts:white_grape_seeds"] },

    { result: "lootjs:apple_jam",           candidates: ['fruitsdelight:apple_jam', 'vintagedelight:apple_sauce_mason_jar', 'brewinandchewin:apple_jelly', 'bakery:apple_jam'] },
    { result: "lootjs:sweetberry_jam",      candidates: ['fruitsdelight:sweetberry_jam', 'vintagedelight:sweet_berry_mason_jar', 'brewinandchewin:sweet_berry_jam', 'bakery:sweetberry_jam'] },

    // === 3. 肉类与海鲜 (Meats & Seafood) ===
    { result: "lootjs:bacon",               candidates: ["farmersdelight:bacon", "farm_and_charm:bacon", "kaleidoscope_cookery:raw_pork_belly"] },
    { result: "lootjs:calamari",            candidates: ["rusticdelight:calamari", "culturaldelights:raw_calamari", "dumplings_delight:calamari"] },
    { result: "lootjs:cooked_calamari",     candidates: ["rusticdelight:cooked_calamari", "culturaldelights:cooked_calamari"] },
    { result: "lootjs:chicken_cuts",        candidates: ["farmersdelight:chicken_cuts", "farm_and_charm:chicken_parts", "kaleidoscope_cookery:raw_cut_small_meats"] },
    { result: "lootjs:cod",                 candidates: ["minecraft:cod"] },
    { result: "lootjs:cooked_bacon",        candidates: ["farmersdelight:cooked_bacon", "kaleidoscope_cookery:cooked_pork_belly"] },
    { result: "lootjs:cooked_chicken_cuts", candidates: ["farmersdelight:cooked_chicken_cuts", "kaleidoscope_cookery:cooked_cut_small_meats"] },
    { result: "lootjs:cooked_ham",          candidates: ["farmersdelight:smoked_ham"] },
    { result: "lootjs:cooked_lamb_chops",   candidates: ["kaleidoscope_cookery:cooked_lamb_chops", "farmersdelight:cooked_mutton_chops"] },
    { result: "lootjs:cooked_minced_beef",  candidates: ["farmersdelight:beef_patty", "kaleidoscope_cookery:cooked_cow_offal"] },
    { result: "lootjs:egg",                 candidates: ["minecraft:egg"] },
    { result: "lootjs:ham",                 candidates: ["farmersdelight:ham"] },
    { result: "lootjs:ham_slice",           candidates: ["kaleidoscope_nether:ham_slice"] },
    { result: "lootjs:minced_beef",         candidates: ["farmersdelight:minced_beef", "farm_and_charm:minced_beef", "kaleidoscope_cookery:raw_cow_offal"] },
    { result: "lootjs:raw_lamb_chops",      candidates: ["kaleidoscope_cookery:raw_lamb_chops", "farmersdelight:mutton_chops", "farm_and_charm:lamb_ham"] },
    { result: "lootjs:salmon",              candidates: ["minecraft:salmon"] },

    // === 4. 谷物、豆类与基础食材 (Grains, Beans & Ingredients) ===
    { result: "lootjs:barley",              candidates: ["farm_and_charm:barley"] },
    { result: "lootjs:barley_seeds",        candidates: ["farm_and_charm:barley_seeds"] },
    { result: "lootjs:raw_cheese_wheel",    candidates: ['casualnessdelight:raw_cheese_wheel', 'brewinandchewin:unripe_flaxen_cheese_wheel', 'trailandtales_delight:curd_block'] },
    { result: "lootjs:cheese_wheel",        candidates: ['casualnessdelight:cheese_wheel', 'brewinandchewin:flaxen_cheese_wheel', 'vintagedelight:cheese_wheel', 'trailandtales_delight:cheese_wheel', 'kitchenkarrot:cheese_wheel'] },
    { result: "lootjs:cheese_slice",        candidates: ['casualnessdelight:cheese_wheel_slice', 'brewinandchewin:flaxen_cheese_wedge', 'vintagedelight:cheese_slice', 'trailandtales_delight:cheese_slice', 'kitchenkarrot:cheese_slice'] },
    { result: "lootjs:cocoabeans",          candidates: ["minecraft:cocoa_beans"] },
    { result: "lootjs:raw_coffee_beans",    candidates: ['youkaishomecoming:green_coffee_bean', "youkaisfeasts:green_coffee_bean", "rusticdelight:coffee_beans", "bakeries:raw_coffee_bean"] },
    { result: "lootjs:roasted_coffee_beans",candidates: ['youkaishomecoming:coffee_beans', "youkaisfeasts:coffee_beans", "rusticdelight:roasted_coffee_beans", "bakeries:coffee_bean"] },
    { result: "lootjs:coffee_powder",       candidates: ['youkaishomecoming:coffee_powder', "youkaisfeasts:coffee_powder", "bakeries:ground_coffee"] },
    { result: "lootjs:cooked_rice",         candidates: ["kaleidoscope_cookery:cooked_rice", "farmersdelight:cooked_rice"] },
    { result: "lootjs:flour",               candidates: ["kaleidoscope_cookery:flour", "farm_and_charm:flour", "create:wheat_flour", "bakeries:whole_wheat_flour"] },
    { result: "lootjs:honey_bottle",        candidates: ["minecraft:honey_bottle"] },
    
    { result: "lootjs:oat",                 candidates: ["farm_and_charm:oat", "vintagedelight:oat"] },
    { result: "lootjs:oat_seeds",           candidates: ["farm_and_charm:oat_seeds", "vintagedelight:oat_seeds"] },
    { result: "lootjs:peanut",              candidates: ["vintagedelight:peanut"] },
    { result: "lootjs:pods",                candidates: ["youkaishomecoming:pods", "youkaisfeasts:pods"] },
    { result: "lootjs:redbean",             candidates: ["youkaishomecoming:redbean", "youkaisfeasts:redbean"] },
    // { result: "lootjs:redbean_seeds",     candidates: ["youkaishomecoming:redbean_seeds", "youkaisfeasts:redbean_seeds"] },
    { result: "lootjs:rice",                candidates: ["kaleidoscope_cookery:rice", "farmersdelight:rice"] },
    { result: "lootjs:roasted_coffee",      candidates: ["rusticdelight:roasted_coffee_beans"] },
    { result: "lootjs:salt",                candidates: ["voidlessframework:salt", "kaleidoscope_chinesefood:salt", "bakeries:salt", "vintagedelight:salt_dust"] },
    { result: "lootjs:soybean",             candidates: ["youkaishomecoming:soybean", "youkaisfeasts:soybean"] },
    { result: "lootjs:soybean_seeds",       candidates: ["youkaishomecoming:soybean_seeds", "youkaisfeasts:soybean_seeds"] }, 
    { result: "lootjs:sugar",               candidates: ["minecraft:sugar"] },
    { result: "lootjs:wheat",               candidates: ["minecraft:wheat"] },
    { result: "lootjs:wheat_seeds",         candidates: ["minecraft:wheat_seeds"] },

    // === 5. 林业与经济作物 (Forestry & Textiles) ===
    { result: "lootjs:acorn",               candidates: ["seeddelight:acorn"] },
    { result: "lootjs:cotton",              candidates: ["rusticdelight:cotton_boll"] },
    { result: "lootjs:pinecone",            candidates: ["seeddelight:pinecone"] },
    { result: "lootjs:sugar_cane",          candidates: ["seeddelight:sugar_cane"] },
    

    // === 6. 矿物与金属材料 (Minerals & Materials) ===
    { result: "lootjs:amethyst",            candidates: ["minecraft:amethyst_shard"] },
    { result: "lootjs:coal",                candidates: ["minecraft:coal"] },
    { result: "lootjs:copper_ingot",        candidates: ["minecraft:copper_ingot"] },
    { result: "lootjs:diamond",             candidates: ["minecraft:diamond"] },
    { result: "lootjs:emerald",             candidates: ["minecraft:emerald"] },
    { result: "lootjs:gold_ingot",          candidates: ["minecraft:gold_ingot"] },
    { result: "lootjs:iron_ingot",          candidates: ["minecraft:iron_ingot"] },
    { result: "lootjs:lapis",               candidates: ["minecraft:lapis_lazuli"] },
    { result: "lootjs:netherite",           candidates: ["minecraft:netherite_ingot"] },
    { result: "lootjs:quartz",              candidates: ["minecraft:quartz"] },
    { result: "lootjs:raw_copper",          candidates: ["minecraft:raw_copper"] },
    { result: "lootjs:raw_gold",            candidates: ["minecraft:raw_gold"] },
    { result: "lootjs:raw_iron",            candidates: ["minecraft:raw_iron"] },
    { result: "lootjs:raw_zinc",            candidates: ["create:raw_zinc"] },
    { result: "lootjs:redstone",            candidates: ["minecraft:redstone"] },
    { result: "lootjs:zinc_ingot",          candidates: ["create:zinc_ingot"] },
    // === 7. 工具类 (Tools) ===
    { result: "lootjs:small_iron_knife",    candidates: ["farmersdelight:iron_knife", "kitchenkarrot:knife", "bakery:bread_knife", "bakeries:bread_knife"] },

];

// ==================== 2. 逻辑处理 ====================
mergeDuplicateItems (DUPLICATE_ITEMS_CONFIG) 
duplicateItemConversion(DUPLICATE_ITEMS_CONFIG);

let crateAndBagRegistry = [
    // === 1. 蔬菜箱 (Vegetable Crates & Bags) ===
    { name: "beetroot_crate",          ids: ["farmersdelight:beetroot_crate", "farm_and_charm:beetroot_bag"] },
    { name: "bell_pepper_green_crate", ids: ["rusticdelight:bell_pepper_green_crate"] },
    { name: "bell_pepper_red_crate",   ids: ["rusticdelight:bell_pepper_red_crate"] },
    { name: "bell_pepper_yellow_crate",ids: ["rusticdelight:bell_pepper_yellow_crate"] },
    { name: "cabbage_crate",           ids: ["farmersdelight:cabbage_crate"] },
    { name: "carrot_crate",            ids: ["farmersdelight:carrot_crate", "farm_and_charm:carrot_bag"] },
    { name: "chinese_cabbage_crate",   ids: ["dumplings_delight:chinese_cabbage_crate"] },
    { name: "corn_crate",              ids: ["farm_and_charm:corn_bag", "corn_delight:corn_crate", "culturaldelights:corn_cob_crate"] },
    { name: "corn_seeds_crate",        ids: ["corn_delight:corn_kernel_bag"] },
    { name: "cucumber_crate",          ids: ["youkaisfeasts:cucumber_crate", "vintagedelight:cucumber_crate", "culturaldelights:cucumber_crate"] },
    { name: "eggplant_crate",          ids: ["dumplings_delight:eggplant_crate", "culturaldelights:eggplant_crate"] },
    { name: "fennel_crate",            ids: ["dumplings_delight:fennel_crate"] },
    { name: "garlic_chive_crate",      ids: ["dumplings_delight:garlic_chive_crate"] },
    { name: "garlic_crate",            ids: ["dumplings_delight:garlic_crate"] },
    { name: "greenonion_crate",        ids: ["dumplings_delight:greenonion_crate"] },
    { name: "lettuce_bag",             ids: ["farm_and_charm:lettuce_bag"] },
    { name: "brown_mushroom_crate",    ids: ["cratedelight:brown_mushroom_crate"] },
    { name: "red_mushroom_crate",      ids: ["cratedelight:red_mushroom_crate"] },
    { name: "onion_crate",             ids: ["farmersdelight:onion_crate", "farm_and_charm:onion_bag"] },
    { name: "pepper_crate",            ids: ["muffins_thaidelight:pepper_crate", "vintagedelight:ghost_pepper_crate"] },
    { name: "poisonous_potato_crate",  ids: ["cratedelight:poisonous_potato_crate"] },
    { name: "potato_crate",            ids: ["farmersdelight:potato_crate", "farm_and_charm:potato_bag"] },
    { name: "pumpkin_slice_crate",     ids: ["cratedelight:pumpkin_slice_crate"] },
    { name: "tomato_crate",            ids: ["farmersdelight:tomato_crate", "farm_and_charm:tomato_bag"] },
    { name: "white_eggplant_crate",    ids: ["culturaldelights:white_eggplant_crate"] },

    // === 2. 水果箱 (Fruit & Berry Crates) ===
    { name: "apple_crate",             ids: ["cratedelight:apple_crate", "fruitsdelight:apple_crate"] },
    { name: "avocado_crate",           ids: ["culturaldelights:avocado_crate"] },
    { name: "bayberry_crate",          ids: ["fruitsdelight:bayberry_crate"] },
    { name: "berry_crate",             ids: ["cratedelight:berry_crate"] },
    { name: "black_grape_crate",       ids: ["youkaisfeasts:black_grape_crate", "youkaishomecoming:black_grape_crate"] },
    { name: "blueberry_crate",         ids: ["fruitsdelight:blueberry_crate"] },
    { name: "cherry_crate",            ids: ["seeddelight:cherry_crate"] },
    { name: "cranberry_crate",         ids: ["fruitsdelight:cranberry_crate"] },
    { name: "fig_crate",               ids: ["fruitsdelight:fig_crate"] },
    { name: "gearo_berry_crate",        ids: ["vintagedelight:gearo_berry_bag"] },
    { name: "glowberry_crate",         ids: ["cratedelight:glowberry_crate"] },
    { name: "hawberry_crate",          ids: ["fruitsdelight:hawberry_crate"] },
    { name: "kiwi_crate",              ids: ["fruitsdelight:kiwi_crate"] },
    { name: "lemon_crate",             ids: ["fruitsdelight:lemon_crate"] },
    { name: "lime_crate",              ids: ["muffins_thaidelight:lime_crate"] },
    { name: "lychee_crate",            ids: ["fruitsdelight:lychee_crate"] },
    { name: "mango_crate",             ids: ["fruitsdelight:mango_crate"] },
    { name: "mangosteen_crate",        ids: ["fruitsdelight:mangosteen_crate"] },
    { name: "orange_crate",            ids: ["fruitsdelight:orange_crate"] },
    { name: "papaya_crate",            ids: ["muffins_thaidelight:papaya_crate"] },
    { name: "peach_crate",             ids: ["fruitsdelight:peach_crate"] },
    { name: "pear_crate",              ids: ["fruitsdelight:pear_crate"] },
    { name: "persimmon_crate",         ids: ["fruitsdelight:persimmon_crate"] },
    { name: "pineapple_crate",         ids: ["fruitsdelight:pineapple_crate", "pineapple_delight:pineapple_crate"] },
    { name: "red_grape_crate",         ids: ["youkaisfeasts:red_grape_crate", "youkaishomecoming:red_grape_crate"] },
    { name: "rosehip_crate",           ids: ["seeddelight:rosehip_crate"] },
    { name: "strawberry_bag",          ids: ["farm_and_charm:strawberry_bag"] },
    { name: "white_grape_crate",       ids: ["youkaisfeasts:white_grape_crate", "youkaishomecoming:white_grape_crate"] },

    // === 3. 肉类与海鲜箱 (Meat & Seafood Crates) ===
    { name: "cod_crate",               ids: ["cratedelight:cod_crate"] },
    { name: "egg_crate",               ids: ["cratedelight:egg_crate"] },
    { name: "salmon_crate",            ids: ["cratedelight:salmon_crate"] },

    // === 4. 谷物、豆类与基础食物袋 (Grains, Beans & Food Bags) ===
    { name: "bread_bag",               ids: ["cratedelight:bread_bag"] },
    { name: "cocoabeans_bag",          ids: ["cratedelight:cocoabeans_bag"] },
    { name: "raw_coffee_beans_bag",    ids: ["rusticdelight:coffee_beans_bag"] },
    { name: "roasted_coffee_beans_bag",ids: ["youkaishomecoming:coffee_bean_bag", "rusticdelight:roasted_coffee_beans_bag"] },
    { name: "cookie_bag",              ids: ["cratedelight:cookie_bag"] },
    { name: "flour_bag",               ids: ["farm_and_charm:flour_bag", "bakeries:wheat_flour_bag"] },
    { name: "hay_block",               ids: ["minecraft:hay_block"] },
    { name: "honey_block",             ids: ["minecraft:honey_block"] },
    { name: "oat_bale",                ids: ["farm_and_charm:oat_ball", "vintagedelight:oat_bag"] },
    { name: "peanut_crate",            ids: ["vintagedelight:peanut_crate"] },
    { name: "pod_crate",               ids: ["youkaisfeasts:pod_crate", "youkaishomecoming:pod_crate"] },
    { name: "redbean_bag",             ids: ["youkaisfeasts:redbean_bag", "youkaishomecoming:redbean_bag"] },
    { name: "rice_bag",                ids: ["farmersdelight:rice_bag"] },
    { name: "rice_panicle_bag",        ids: ["farmersdelight:rice_panicle_bag", "farmersdelight:rice_bale"] },
    { name: "roasted_coffee_bag",      ids: ["rusticdelight:roasted_coffee_beans_bag"] },
    { name: "soybean_bag",             ids: ["youkaisfeasts:soybean_bag", "youkaishomecoming:soybean_bag"] },
    { name: "sugar_bag",               ids: ["cratedelight:sugar_bag"] },

    // === 5. 林业与经济作物袋 (Forestry & Textile Bags) ===
    { name: "acorn_bag",               ids: ["seeddelight:acorn_bag"] },
    { name: "cotton_crate",            ids: ["rusticdelight:cotton_boll_crate"] },
    { name: "pinecone_bag",            ids: ["seeddelight:pinecone_bag"] }
];

// 映射转换并直接覆盖原数组名
crateAndBagRegistry = crateAndBagRegistry.map(item => ({
    result: `lootjs:${item.name}`, 
    candidates: item.ids
}));

mergeDuplicateItems(crateAndBagRegistry);

const mergeItem = DUPLICATE_ITEMS_CONFIG.concat(crateAndBagRegistry);

let finalFoodSupplyRegistry = [
    // === 1. 蔬菜类 (Vegetables) ===
    { name: "beetroot",           singles: ["lootjs:beetroot"],                     crates: ["lootjs:beetroot_crate"] },
    { name: "beetroot_seeds",     singles: ["lootjs:beetroot_seeds"],               crates: ["cratedelight:beetroot_seeds_bag"] },
    { name: "bell_pepper_green",  singles: ["lootjs:bell_pepper_green"],            crates: ["lootjs:bell_pepper_green_crate"] },
    { name: "bell_pepper_red",    singles: ["lootjs:bell_pepper_red"],              crates: ["lootjs:bell_pepper_red_crate"] },
    { name: "bell_pepper_yellow", singles: ["lootjs:bell_pepper_yellow"],           crates: ["lootjs:bell_pepper_yellow_crate"] },
    { name: "cabbage",            singles: ["lootjs:cabbage"],                      crates: ["lootjs:cabbage_crate"] },
    { name: "carrot",             singles: ["lootjs:carrot"],                       crates: ["lootjs:carrot_crate"] },
    { name: "chinese_cabbage",    singles: ["lootjs:chinese_cabbage"],              crates: ["lootjs:chinese_cabbage_crate"] },
    { name: "corn",               singles: ["lootjs:corn"],                         crates: ["lootjs:corn_crate"] },
    { name: "corn_seeds",         singles: ["lootjs:corn_seeds"],                   crates: ["lootjs:corn_seeds_crate"] },
    { name: "cucumber",           singles: ["lootjs:cucumber"],                     crates: ["lootjs:cucumber_crate"] },
    { name: "eggplant",           singles: ["lootjs:eggplant"],                     crates: ["lootjs:eggplant_crate"] },
    { name: "fennel",             singles: ["lootjs:fennel"],                       crates: ["lootjs:fennel_crate"] },
    { name: "garlic",             singles: ["lootjs:garlic"],                       crates: ["lootjs:garlic_crate"] },
    { name: "garlic_chive",       singles: ["lootjs:garlic_chive"],                 crates: ["lootjs:garlic_chive_crate"] },
    { name: "greenonion",         singles: ["lootjs:greenonion"],                   crates: ["lootjs:greenonion_crate"] },
    { name: "kelp",               singles: ["lootjs:kelp"],                         crates: ["minecraft:dried_kelp_block"] },
    { name: "lettuce",            singles: ["lootjs:lettuce"],                      crates: ["lootjs:lettuce_bag"] },
    { name: "brown_mushroom",     singles: ["lootjs:brown_mushroom"],               crates: ["lootjs:brown_mushroom_crate"] },
    { name: "red_mushroom",       singles: ["lootjs:red_mushroom"],                 crates: ["lootjs:red_mushroom_crate"] },
    { name: "onion",              singles: ["lootjs:onion"],                        crates: ["lootjs:onion_crate"] },
    { name: "pepper",             singles: ["lootjs:pepper"],                       crates: ["lootjs:pepper_crate"] },
    { name: "poisonous_potato",   singles: ["lootjs:poisonous_potato"],             crates: ["lootjs:poisonous_potato_crate"] },
    { name: "potato",             singles: ["lootjs:potato"],                       crates: ["lootjs:potato_crate"] },
    { name: "pumpkin_slice",      singles: ["lootjs:pumpkin_slice"],                crates: ["lootjs:pumpkin_slice_crate"] },
    { name: "pumpkin_seeds",      singles: ["lootjs:pumpkin_seeds"],                crates: ["cratedelight:pumpkin_seeds_bag"] },
    { name: "tomato",             singles: ["lootjs:tomato"],                       crates: ["lootjs:tomato_crate"] },
    { name: "white_eggplant",     singles: ["lootjs:white_eggplant"],               crates: ["lootjs:white_eggplant_crate"] },

    // === 2. 水果类 (Fruits & Berries) ===
    { name: "apple",              singles: ["lootjs:apple"],                        crates: ["lootjs:apple_crate"] },
    { name: "avocado",            singles: ["lootjs:avocado"],                      crates: ["lootjs:avocado_crate"] },
    { name: "bayberry",           singles: ["lootjs:bayberry"],                     crates: ["lootjs:bayberry_crate"] },
    { name: "berry",              singles: ["lootjs:berry"],                        crates: ["lootjs:berry_crate"] },
    { name: "black_grape",        singles: ["lootjs:black_grape"],                  crates: ["lootjs:black_grape_crate"] },
    { name: "blueberry",          singles: ["lootjs:blueberry"],                    crates: ["lootjs:blueberry_crate"] },
    { name: "cherry",             singles: ["lootjs:cherry"],                       crates: ["lootjs:cherry_crate"] },
    { name: "cranberry",          singles: ["lootjs:cranberry"],                    crates: ["lootjs:cranberry_crate"] },
    { name: "durian_flesh",       singles: ["lootjs:durian_flesh"],                 crates: ["lootjs:durian"] },
    { name: "fig",                singles: ["lootjs:fig"],                          crates: ["lootjs:fig_crate"] },
    { name: "gearo_berry",        singles: ["lootjs:gearo_berry"],                  crates: ["lootjs:gearo_berry_crate"] },
    { name: "glowberry",          singles: ["lootjs:glowberry"],                    crates: ["lootjs:glowberry_crate"] },
    { name: "hamimelon_slice",    singles: ["lootjs:hamimelon_slice"],              crates: ["lootjs:hamimelon"] },
    { name: "hawberry",           singles: ["lootjs:hawberry"],                     crates: ["lootjs:hawberry_crate"] },
    { name: "kiwi",               singles: ["lootjs:kiwi"],                         crates: ["lootjs:kiwi_crate"] },
    { name: "lemon",              singles: ["lootjs:lemon"],                        crates: ["lootjs:lemon_crate"] },
    { name: "lime",               singles: ["lootjs:lime"],                         crates: ["lootjs:lime_crate"] },
    { name: "lychee",             singles: ["lootjs:lychee"],                       crates: ["lootjs:lychee_crate"] },
    { name: "mango",              singles: ["lootjs:mango"],                        crates: ["lootjs:mango_crate"] },
    { name: "mangosteen",         singles: ["lootjs:mangosteen"],                   crates: ["lootjs:mangosteen_crate"] },
    { name: "melon_slice",        singles: ["lootjs:melon_slice"],                  crates: ["lootjs:melon"] },
    { name: "melon_seeds",        singles: ["lootjs:melon_seeds"],                  crates: ["cratedelight:melon_seeds_bag"] },
    { name: "orange",             singles: ["lootjs:orange"],                       crates: ["lootjs:orange_crate"] },
    { name: "papaya",             singles: ["lootjs:papaya"],                       crates: ["lootjs:papaya_crate"] },
    { name: "peach",              singles: ["lootjs:peach"],                        crates: ["lootjs:peach_crate"] },
    { name: "pear",               singles: ["lootjs:pear"],                         crates: ["lootjs:pear_crate"] },
    { name: "persimmon",          singles: ["lootjs:persimmon"],                    crates: ["lootjs:persimmon_crate"] },
    { name: "pineapple_slice",    singles: ["lootjs:pineapple_slice"],              crates: ["lootjs:pineapple"] },
    { name: "red_grape",          singles: ["lootjs:red_grape"],                    crates: ["lootjs:red_grape_crate"] },
    { name: "rosehip",            singles: ["lootjs:rosehip"],                      crates: ["lootjs:rosehip_crate"] },
    { name: "strawberry",         singles: ["lootjs:strawberry"],                   crates: ["lootjs:strawberry_bag"] },
    { name: "white_grape",        singles: ["lootjs:white_grape"],                  crates: ["lootjs:white_grape_crate"] },

    // === 3. 肉类与海鲜 (Meats & Seafood) ===
    { name: "cod",                singles: ["lootjs:cod"],                          crates: ["lootjs:cod_crate"] },
    { name: "egg",                singles: ["lootjs:egg"],                          crates: ["lootjs:egg_crate"] },
    { name: "salmon",             singles: ["lootjs:salmon"],                       crates: ["lootjs:salmon_crate"] },

    // === 4. 谷物、豆类与基础食材 (Grains, Beans & Ingredients) ===
    { name: "cheese_slice",       singles: ["lootjs:cheese_slice"],                 crates: ["lootjs:cheese_wheel"] },
    { name: "cocoabeans",         singles: ["lootjs:cocoabeans"],                   crates: ["lootjs:cocoabeans_bag"] },
    { name: "raw_coffee_beans",   singles: ["lootjs:raw_coffee_beans"],             crates: ["lootjs:raw_coffee_beans_bag"] },
    { name: "roasted_coffee_beans", singles: ["lootjs:roasted_coffee_beans"],       crates: ["lootjs:roasted_coffee_beans_bag"] },
    { name: "flour",              singles: ["lootjs:flour"],                        crates: ["lootjs:flour_bag"] },
    { name: "honey_bottle",       singles: ["lootjs:honey_bottle"],                 crates: ["lootjs:honey_block"] },
    { name: "oat",                singles: ["lootjs:oat"],                          crates: ["lootjs:oat_bale"] },
    { name: "peanut",             singles: ["lootjs:peanut"],                       crates: ["lootjs:peanut_crate"] },
    { name: "pods",               singles: ["lootjs:pods"],                         crates: ["lootjs:pod_crate"] },
    { name: "redbean",            singles: ["lootjs:redbean"],                      crates: ["lootjs:redbean_bag"] },
    { name: "rice",               singles: ["lootjs:rice"],                         crates: ["lootjs:rice_bag"] },
    { name: "roasted_coffee",     singles: ["lootjs:roasted_coffee"],               crates: ["lootjs:roasted_coffee_bag"] },
    { name: "soybean",            singles: ["lootjs:soybean"],                      crates: ["lootjs:soybean_bag"] },
    { name: "sugar",              singles: ["lootjs:sugar"],                        crates: ["lootjs:sugar_bag"] },
    { name: "wheat",              singles: ["lootjs:wheat"],                        crates: ["lootjs:hay_block"] },
    { name: "wheat_seeds",        singles: ["lootjs:wheat_seeds"],                  crates: ["cratedelight:wheat_seeds_bag"] },

    // === 5. 林业与经济作物 (Forestry & Textiles) ===
    { name: "acorn",              singles: ["lootjs:acorn"],                        crates: ["lootjs:acorn_bag"] },
    { name: "cotton",             singles: ["lootjs:cotton"],                       crates: ["lootjs:cotton_crate"] },
    { name: "pinecone",           singles: ["lootjs:pinecone"],                     crates: ["lootjs:pinecone_bag"] },

    // === 6. 矿物与金属材料 (Minerals & Materials) ===
    { name: "amethyst",           singles: ["lootjs:amethyst"],                     crates: ["minecraft:amethyst_block"] },
    { name: "coal",               singles: ["lootjs:coal"],                         crates: ["minecraft:coal_block"] },
    { name: "copper_ingot",       singles: ["lootjs:copper_ingot"],                 crates: ["minecraft:copper_block"] },
    { name: "diamond",            singles: ["lootjs:diamond"],                      crates: ["minecraft:diamond_block"] },
    { name: "emerald",            singles: ["lootjs:emerald"],                      crates: ["minecraft:emerald_block"] },
    { name: "gold_ingot",         singles: ["lootjs:gold_ingot"],                   crates: ["minecraft:gold_block"] },
    { name: "iron_ingot",         singles: ["lootjs:iron_ingot"],                   crates: ["minecraft:iron_block"] },
    { name: "lapis",              singles: ["lootjs:lapis"],                        crates: ["minecraft:lapis_block"] },
    { name: "netherite",          singles: ["lootjs:netherite"],                    crates: ["minecraft:netherite_block"] },
    { name: "quartz",             singles: ["lootjs:quartz"],                       crates: ["minecraft:quartz_block"] },
    { name: "raw_copper",         singles: ["lootjs:raw_copper"],                   crates: ["minecraft:raw_copper_block"] },
    { name: "raw_gold",           singles: ["lootjs:raw_gold"],                     crates: ["minecraft:raw_gold_block"] },
    { name: "raw_iron",           singles: ["lootjs:raw_iron"],                     crates: ["minecraft:raw_iron_block"] },
    { name: "raw_zinc",           singles: ["lootjs:raw_zinc"],                     crates: ["create:raw_zinc_block"] },
    { name: "redstone",           singles: ["lootjs:redstone"],                     crates: ["minecraft:redstone_block"] },
    { name: "zinc_ingot",         singles: ["lootjs:zinc_ingot"],                   crates: ["create:zinc_block"] }
];

// =================================================================
// 第二步：将单个食物与之前打包好的箱/袋战利品表进行最终关联
// =================================================================
createLootTable2Pool(finalFoodSupplyRegistry);