// ==================== 1. 配置数组 ====================
let DUPLICATE_ITEMS_CONFIG = [

    // === 1. 蔬菜类 (Vegetables) ===
    { result: "lootjs:beetroot",                    candidates: ["minecraft:beetroot"] },
    { result: "lootjs:beetroot_seeds",              candidates: ["minecraft:beetroot_seeds"] },
    { result: "lootjs:bell_pepper_seeds",           candidates: ["rusticdelight:bell_pepper_seeds", 'veggiesdelight:bellpepper_seeds'] },
    { result: "lootjs:pale_bell_pepper_seeds",      candidates: ["rusticdelight:pale_bell_pepper_seeds"] },
    { result: "lootjs:dark_bell_pepper_seeds",      candidates: ["rusticdelight:dark_bell_pepper_seeds"] },
    { result: "lootjs:bell_pepper_green",           candidates: ["rusticdelight:bell_pepper_green"] },
    { result: "lootjs:bell_pepper_red",             candidates: ["rusticdelight:bell_pepper_red"] },
    { result: "lootjs:bell_pepper_yellow",          candidates: ["rusticdelight:bell_pepper_yellow", 'veggiesdelight:bellpepper'] },
    { result: "lootjs:bell_pepper_pink",            candidates: ["rusticdelight:bell_pepper_pink"] },
    { result: "lootjs:bell_pepper_orange",          candidates: ["rusticdelight:bell_pepper_orange"] },
    { result: "lootjs:bell_pepper_white",           candidates: ["rusticdelight:bell_pepper_white"] },
    { result: "lootjs:bell_pepper_blue",            candidates: ["rusticdelight:bell_pepper_blue"] },
    { result: "lootjs:bell_pepper_purple",          candidates: ["rusticdelight:bell_pepper_purple"] },
    { result: "lootjs:bell_pepper_black",           candidates: ["rusticdelight:bell_pepper_black"] },
    { result: "lootjs:cabbage",                     candidates: ["farmersdelight:cabbage"] },
    { result: "lootjs:cabbage_seeds",               candidates: ["farmersdelight:cabbage_seeds"] },
    { result: "lootjs:carrot",                      candidates: ["minecraft:carrot"] },
    { result: "lootjs:chinese_cabbage",             candidates: ["dumplings_delight:chinese_cabbage"] },
    { result: "lootjs:chinese_cabbage_seeds",       candidates: ["dumplings_delight:chinese_cabbage_seeds"] },
    { result: "lootjs:corn",                        candidates: ["farm_and_charm:corn", "corn_delight:corn", "culturaldelights:corn_cob"] },
    { result: "lootjs:corn_seeds",                  candidates: ["farm_and_charm:kernels", "corn_delight:corn_seeds", "culturaldelights:corn_kernels"] },    
    { result: "lootjs:cucumber",                    candidates: ["youkaisfeasts:cucumber", "youkaishomecoming:cucumber", "vintagedelight:cucumber", "culturaldelights:cucumber"] },
    { result: "lootjs:cucumber_seeds",              candidates: ["youkaisfeasts:cucumber_seeds", "youkaishomecoming:cucumber_seeds", "vintagedelight:cucumber_seeds", "culturaldelights:cucumber_seeds"] },
    { result: "lootjs:eggplant",                    candidates: ["dumplings_delight:eggplant", "culturaldelights:eggplant"] },
    { result: "lootjs:eggplant_seeds",              candidates: ["dumplings_delight:eggplant_seeds", "culturaldelights:eggplant_seeds"] },
    { result: "lootjs:fennel",                      candidates: ["dumplings_delight:fennel"] },
    { result: "lootjs:fennel_seeds",                candidates: ["dumplings_delight:fennel_seeds"] },
    { result: "lootjs:garlic",                      candidates: ["dumplings_delight:garlic", "veggiesdelight:garlic"] },
    { result: "lootjs:garlic_clove",                candidates: ["dumplings_delight:garlic_clove", "veggiesdelight:garlic_clove"] },
    { result: "lootjs:garlic_chive",                candidates: ["dumplings_delight:garlic_chive"] },
    { result: "lootjs:garlic_chive_seeds",          candidates: ["dumplings_delight:garlic_chive_seeds"] },
    { result: "lootjs:greenonion",                  candidates: ["dumplings_delight:greenonion"] },
    { result: "lootjs:hops",                        candidates: ["brewery:hops"] },
    { result: "lootjs:kelp",                        candidates: ["minecraft:kelp"] },
    { result: "lootjs:lettuce",                     candidates: ["kaleidoscope_cookery:lettuce", "farm_and_charm:lettuce"] },
    { result: "lootjs:lettuce_seeds",               candidates: ["kaleidoscope_cookery:lettuce_seed", "farm_and_charm:lettuce_seeds"] },
    { result: "lootjs:brown_mushroom",              candidates: ["minecraft:brown_mushroom"] },
    { result: "lootjs:red_mushroom",                candidates: ["minecraft:red_mushroom"] },
    { result: "lootjs:onion",                       candidates: ["farmersdelight:onion", "farm_and_charm:onion"] },
    { result: "lootjs:pepper",                      candidates: ["kaleidoscope_cookery:red_chili", /* "kaleidoscope_cookery:green_chili",  */"muffins_thaidelight:pepper", "vintagedelight:ghost_pepper", "casualnessdelight:capsicum"] },
    { result: "lootjs:pepper_seeds",                candidates: ["kaleidoscope_cookery:chili_seed", "muffins_thaidelight:pepper_seeds", "vintagedelight:ghost_pepper_seeds", "casualnessdelight:capsicum_seeds"] },
    { result: "lootjs:pickle",                      candidates: ["vintagedelight:pickle", "culturaldelights:pickle"] },
    { result: "lootjs:poisonous_potato",            candidates: ["minecraft:poisonous_potato"] },
    { result: "lootjs:potato",                      candidates: ["minecraft:potato"] },
    { result: "lootjs:pumpkin",                     candidates: ["minecraft:pumpkin"] },
    { result: "lootjs:pumpkin_slice",               candidates: ["farmersdelight:pumpkin_slice"] },
    { result: "lootjs:pumpkin_seeds",               candidates: ["minecraft:pumpkin_seeds"] },
    { result: "lootjs:rotten_tomato",               candidates: ["farmersdelight:rotten_tomato", "farm_and_charm:rotten_tomato"] },
    { result: "lootjs:tomato",                      candidates: ["kaleidoscope_cookery:tomato", "farmersdelight:tomato", "farm_and_charm:tomato", "bakeries:tomato"] },
    { result: "lootjs:tomato_seeds",                candidates: ["kaleidoscope_cookery:tomato_seed", "farmersdelight:tomato_seeds", "farm_and_charm:tomato_seeds"] },
    { result: "lootjs:white_eggplant",              candidates: ["culturaldelights:white_eggplant"] },
    { result: "lootjs:broccoli",                    candidates: ["veggiesdelight:broccoli"] },
    { result: "lootjs:broccoli_seeds",              candidates: ["veggiesdelight:broccoli_seeds"] },
    { result: "lootjs:cauliflower",                 candidates: ["veggiesdelight:cauliflower"] },
    { result: "lootjs:cauliflower_seeds",           candidates: ["veggiesdelight:cauliflower_seeds"] },
    { result: "lootjs:turnip",                      candidates: ["veggiesdelight:turnip"] },
    { result: "lootjs:turnip_seeds",                candidates: ["veggiesdelight:turnip_seeds"] },
    { result: "lootjs:zucchini",                    candidates: ["veggiesdelight:zucchini"] },
    { result: "lootjs:zucchini_seeds",              candidates: ["veggiesdelight:zucchini_seeds"] },
    { result: "lootjs:chickpea",                    candidates: ["ramadandelight:chickpea"] },
    { result: "lootjs:parsley",                     candidates: ["ramadandelight:parsley"] },
    { result: "lootjs:parsley_seeds",               candidates: ["ramadandelight:parsley_seeds"] },
    { result: "lootjs:mint_leaves",                 candidates: ["neapolitan:mint_leaves"] },
    { result: "lootjs:mint_sprout",                 candidates: ["neapolitan:mint_sprout"] },
    { result: "lootjs:adzuki_beans",                candidates: ["neapolitan:adzuki_beans"] },
    { result: "lootjs:vanilla_pods",                candidates: ["neapolitan:vanilla_pods"] },

    // === 2. 水果类 (Fruits & Berries) ===
    { result: "lootjs:banana",                      candidates: ["neapolitan:banana"] },
    { result: "lootjs:banana_frond",                candidates: ["neapolitan:banana_frond"] },
    { result: "lootjs:apple",                       candidates: ["minecraft:apple"] },
    { result: "lootjs:apple_sapling",               candidates: ["fruitsdelight:apple_sapling"] },
    { result: "lootjs:avocado",                     candidates: ["culturaldelights:avocado"] },
    { result: "lootjs:avocado_sapling",             candidates: ["culturaldelights:avocado_sapling"] },
    { result: "lootjs:bayberry",                    candidates: ["fruitsdelight:bayberry"] },
    { result: "lootjs:bayberry_sapling",            candidates: ["fruitsdelight:bayberry_sapling"] },
    { result: "lootjs:berry",                       candidates: ["minecraft:sweet_berries"] },
    { result: "lootjs:black_grape",                 candidates: ["youkaishomecoming:black_grape", "youkaisfeasts:black_grape"] },
    { result: "lootjs:black_grape_seeds",           candidates: ["youkaishomecoming:black_grape_seeds", "youkaisfeasts:black_grape_seeds"] },
    { result: "lootjs:blueberry",                   candidates: ["fruitsdelight:blueberry"] },
    { result: "lootjs:cherry",                      candidates: ["seeddelight:cherry"] },
    { result: "lootjs:cranberry",                   candidates: ["fruitsdelight:cranberry"] },
    { result: "lootjs:durian_sapling",              candidates: ["fruitsdelight:durian_sapling"] },
    { result: "lootjs:durian_flesh",                candidates: ["fruitsdelight:durian_flesh"] },
    { result: "lootjs:durian_block",                candidates: ["fruitsdelight:durian"] },
    { result: "lootjs:fig",                         candidates: ["fruitsdelight:fig"] },
    { result: "lootjs:fig_sapling",                 candidates: ["fruitsdelight:fig_sapling"] },
    { result: "lootjs:gearo_berry",                 candidates: ["vintagedelight:gearo_berry"] },
    { result: "lootjs:glowberry",                   candidates: ["minecraft:glow_berries"] },
    { result: "lootjs:glowberry_seeds",             candidates: ["berry_good:glow_berry_pips"] },
    { result: "lootjs:hamimelon_block",             candidates: ["fruitsdelight:hamimelon"] },
    { result: "lootjs:hamimelon_slice",             candidates: ["fruitsdelight:hamimelon_slice"] },
    { result: "lootjs:hamimelon_seeds",             candidates: ["fruitsdelight:hamimelon_seeds"] },
    { result: "lootjs:hawberry",                    candidates: ["fruitsdelight:hawberry"] },
    { result: "lootjs:hawberry_sapling",            candidates: ["fruitsdelight:hawberry_sapling"] },
    { result: "lootjs:kiwi",                        candidates: ["fruitsdelight:kiwi"] },
    { result: "lootjs:kiwi_sapling",                candidates: ["fruitsdelight:kiwi_sapling"] },
    { result: "lootjs:lemon",                       candidates: ["fruitsdelight:lemon"] },
    { result: "lootjs:lemon_seeds",                 candidates: ["fruitsdelight:lemon_seeds"] },
    { result: "lootjs:lime",                        candidates: ["muffins_thaidelight:lime"] },
    { result: "lootjs:lime_sapling",                candidates: ["muffins_thaidelight:lime_sapling"] },
    { result: "lootjs:lychee",                      candidates: ["fruitsdelight:lychee"] },
    { result: "lootjs:lychee_sapling",              candidates: ["fruitsdelight:lychee_sapling"] },
    { result: "lootjs:mango",                       candidates: ["fruitsdelight:mango"] },
    { result: "lootjs:mango_sapling",               candidates: ["fruitsdelight:mango_sapling"] },
    { result: "lootjs:mangosteen",                  candidates: ["fruitsdelight:mangosteen"] },
    { result: "lootjs:mangosteen_sapling",          candidates: ["fruitsdelight:mangosteen_sapling"] },
    { result: "lootjs:melon_block",                 candidates: ["minecraft:melon"] },
    { result: "lootjs:melon_slice",                 candidates: ["minecraft:melon_slice"] },
    { result: "lootjs:melon_seeds",                 candidates: ["minecraft:melon_seeds"] },
    { result: "lootjs:orange",                      candidates: ["fruitsdelight:orange"] },
    { result: "lootjs:orange_sapling",              candidates: ["fruitsdelight:orange_sapling"] },
    { result: "lootjs:papaya",                      candidates: ["muffins_thaidelight:papaya"] },
    { result: "lootjs:peach",                       candidates: ["fruitsdelight:peach"] },
    { result: "lootjs:peach_sapling",               candidates: ["fruitsdelight:peach_sapling"] },
    { result: "lootjs:pear",                        candidates: ["fruitsdelight:pear"] },
    { result: "lootjs:pear_sapling",                candidates: ["fruitsdelight:pear_sapling"] },
    { result: "lootjs:persimmon",                   candidates: ["fruitsdelight:persimmon"] },
    { result: "lootjs:persimmon_sapling",           candidates: ["fruitsdelight:persimmon_sapling"] },
    { result: "lootjs:pineapple",                   candidates: ["fruitsdelight:pineapple", "pineapple_delight:pineapple"] },
    { result: "lootjs:pineapple_slice",             candidates: ["fruitsdelight:pineapple_slice", "pineapple_delight:pineapple_slice"] },
    { result: "lootjs:pineapple_sapling",           candidates: ["fruitsdelight:pineapple_sapling", "pineapple_delight:pineapple_crop"] },
    { result: "lootjs:red_grape",                   candidates: ["youkaishomecoming:red_grape", "youkaisfeasts:red_grape"] },
    { result: "lootjs:red_grape_seeds",             candidates: ["youkaishomecoming:red_grape_seeds", "youkaisfeasts:red_grape_seeds"] },
    { result: "lootjs:rosehip",                     candidates: ["seeddelight:rosehip"] },
    { result: "lootjs:strawberry",                  candidates: ["farm_and_charm:strawberry", "neapolitan:strawberries"] },
    { result: "lootjs:strawberry_seeds",            candidates: ["farm_and_charm:strawberry_seeds", "neapolitan:strawberry_pips"] },
    { result: "lootjs:sweetberry",                  candidates: ["minecraft:sweet_berries"] },
    { result: "lootjs:sweetberry_pips",             candidates: ["berry_good:sweet_berry_pips"] },
    { result: "lootjs:white_grape",                 candidates: ["youkaishomecoming:white_grape", "youkaisfeasts:white_grape"] },
    { result: "lootjs:white_grape_seeds",           candidates: ["youkaishomecoming:white_grape_seeds", "youkaisfeasts:white_grape_seeds"] },
    { result: "lootjs:date",                        candidates: ["ramadandelight:date"] },
    { result: "lootjs:date_sapling",                candidates: ["ramadandelight:palm_sapling"] },
    
    { result: "lootjs:apple_jam",                   candidates: ['fruitsdelight:apple_jam', 'vintagedelight:apple_sauce_mason_jar', 'brewinandchewin:apple_jelly', 'bakery:apple_jam'] },
    { result: "lootjs:glowberry_jam",               candidates: ['fruitsdelight:glowberry_jam', 'vintagedelight:glow_berry_mason_jar', 'brewinandchewin:glow_berry_marmalade', 'bakery:glowberry_jam'] },    
    { result: "lootjs:sweetberry_jam",              candidates: ['fruitsdelight:sweetberry_jam', 'vintagedelight:sweet_berry_mason_jar', 'brewinandchewin:sweet_berry_jam', 'bakery:sweetberry_jam'] },
    { result: "lootjs:golden_carrot",               candidates: ["minecraft:golden_carrot"] },
    { result: "lootjs:golden_apple",                candidates: ["minecraft:golden_apple"] },

    // === 3. 肉类与海鲜 (Meats & Seafood) ===

    { result: "lootjs:bacon",                       candidates: ["farmersdelight:bacon", "farm_and_charm:bacon", "kaleidoscope_cookery:raw_pork_belly"] },
    { result: "lootjs:cooked_bacon",                candidates: ["farmersdelight:cooked_bacon", "kaleidoscope_cookery:cooked_pork_belly"] },
    { result: "lootjs:ham",                         candidates: ["farmersdelight:ham"] },
    { result: "lootjs:cooked_ham",                  candidates: ["farmersdelight:smoked_ham"] },
    { result: "lootjs:ham_slice",                   candidates: ["kaleidoscope_nether:ham_slice"] },

    { result: "lootjs:chicken_cuts",                candidates: ["farmersdelight:chicken_cuts", "farm_and_charm:chicken_parts", "kaleidoscope_cookery:raw_cut_small_meats"] },
    { result: "lootjs:cooked_chicken_cuts",         candidates: ["farmersdelight:cooked_chicken_cuts", "kaleidoscope_cookery:cooked_cut_small_meats"] },

    { result: "lootjs:minced_beef",                 candidates: ["farmersdelight:minced_beef", "farm_and_charm:minced_beef", "kaleidoscope_cookery:raw_cow_offal"] },
    { result: "lootjs:cooked_minced_beef",          candidates: ["farmersdelight:beef_patty", "kaleidoscope_cookery:cooked_cow_offal"] },

    { result: "lootjs:raw_lamb_chops",              candidates: ["kaleidoscope_cookery:raw_lamb_chops", "farmersdelight:mutton_chops", "farm_and_charm:lamb_ham"] },
    { result: "lootjs:cooked_lamb_chops",           candidates: ["kaleidoscope_cookery:cooked_lamb_chops", "farmersdelight:cooked_mutton_chops"] },

    { result: "lootjs:calamari",                    candidates: ["rusticdelight:calamari", "culturaldelights:raw_calamari", "dumplings_delight:calamari", 'crabbersdelight:raw_squid_tentacles'] },
    { result: "lootjs:cooked_calamari",             candidates: ["rusticdelight:cooked_calamari", "culturaldelights:cooked_calamari", 'crabbersdelight:cooked_squid_tentacles'] },

    // { result: "lootjs:crab",                        candidates: ["crabbersdelight:crab", 'youkaishomecoming:crab'] },
    // { result: "lootjs:cooked_crab",                 candidates: ["crabbersdelight:cooked_crab", 'youkaishomecoming:steamed_crab'] },
    // { result: "lootjs:crab_roe",                    candidates: ['youkaishomecoming:crab_roe'] },
    // { result: "lootjs:clawster",                    candidates: ["crabbersdelight:clawster"] },
    // { result: "lootjs:cooked_clawster",             candidates: ["crabbersdelight:cooked_clawster"] },
    // { result: "lootjs:shrimp",                      candidates: ["crabbersdelight:shrimp"] },
    // { result: "lootjs:cooked_shrimp",               candidates: ["crabbersdelight:cooked_shrimp"] },
    // { result: "lootjs:clam",                        candidates: ["crabbersdelight:clam"] },
    // { result: "lootjs:cooked_clam",                 candidates: ["crabbersdelight:cooked_clam"] },

    // { result: "lootjs:cod",                         candidates: ["minecraft:cod"] },
    // { result: "lootjs:cooked_cod",                  candidates: ["minecraft:cooked_cod"] },
    // { result: "lootjs:salmon",                      candidates: ["minecraft:salmon"] },
    // { result: "lootjs:cooked_salmon",               candidates: ["minecraft:cooked_salmon"] },
    // { result: "lootjs:pufferfish",                  candidates: ["minecraft:pufferfish"] },
    // { result: "lootjs:tropical_fish",               candidates: ["minecraft:tropical_fish"] },
    // { result: "lootjs:egg",                         candidates: ["minecraft:egg"] },
    // { result: "lootjs:cooked_egg",                  candidates: ['vanillacookbook:cooked_egg', 'mynethersdelight:boiled_egg', 'kaleidoscope_cookery:fried_egg'] },


    // ===== 蟹/海鲜类 =====
    { result: "lootjs:crab",                        candidates: ["crabbersdelight:crab", 'youkaishomecoming:crab'] },
    { result: "lootjs:cooked_crab",                 candidates: ["crabbersdelight:cooked_crab", 'youkaishomecoming:cooked_crab'] },
    { result: "lootjs:crab_roe",                    candidates: ['youkaishomecoming:crab_roe'] },
    { result: "lootjs:cooked_crab_roe",             candidates: ['youkaishomecoming:cooked_crab_roe'] },
    { result: "lootjs:crab_claw",                   candidates: ["crabbersdelight:crab_claw"] },     
    { result: "lootjs:crab_legs",                   candidates: ["crabbersdelight:crab_legs"] },     
    { result: "lootjs:clawster",                    candidates: ["crabbersdelight:clawster"] },
    { result: "lootjs:cooked_clawster",             candidates: ["crabbersdelight:cooked_clawster"] },
    { result: "lootjs:shrimp",                      candidates: ["crabbersdelight:shrimp"] },
    { result: "lootjs:cooked_shrimp",               candidates: ["crabbersdelight:cooked_shrimp"] },
    { result: "lootjs:clam",                        candidates: ["crabbersdelight:clam"] },
    { result: "lootjs:raw_clam_meat",               candidates: ["crabbersdelight:raw_clam_meat"] }, 
    { result: "lootjs:cooked_clam_meat",            candidates: ["crabbersdelight:cooked_clam_meat"] },

    // ===== 鱼类 =====
    { result: "lootjs:cod",                         candidates: ["minecraft:cod"] },
    { result: "lootjs:cooked_cod",                  candidates: ["minecraft:cooked_cod"] },
    { result: "lootjs:cod_slice",                   candidates: ["farmersdelight:cod_slice"] },
    { result: "lootjs:cooked_cod_slice",            candidates: ["farmersdelight:cooked_cod_slice"] },  

    { result: "lootjs:salmon",                      candidates: ["minecraft:salmon"] },
    { result: "lootjs:cooked_salmon",               candidates: ["minecraft:cooked_salmon"] },
    { result: "lootjs:salmon_slice",                candidates: ["farmersdelight:salmon_slice"] },
    { result: "lootjs:cooked_salmon_slice",         candidates: ["farmersdelight:cooked_salmon_slice"] }, 

    { result: "lootjs:pufferfish",                  candidates: ["minecraft:pufferfish"] },
    { result: "lootjs:pufferfish_slice",            candidates: ["crabbersdelight:pufferfish_slice"] },
    { result: "lootjs:cooked_pufferfish_slice",     candidates: ["crabbersdelight:cooked_pufferfish_slice"] }, 

    { result: "lootjs:tropical_fish",               candidates: ["minecraft:tropical_fish"] },
    { result: "lootjs:tropical_fish_slice",         candidates: ["crabbersdelight:tropical_fish_slice"] },
    { result: "lootjs:cooked_tropical_fish_slice",  candidates: ["crabbersdelight:cooked_tropical_fish_slice"] },
    { result: "lootjs:cooked_tropical_fish",        candidates: ["crabbersdelight:cooked_tropical_fish"] },

    { result: "lootjs:roe",                         candidates: ["youkaishomecoming:roe"] },         
    { result: "lootjs:raw_lamprey_fillet",          candidates: ["youkaishomecoming:raw_lamprey_fillet"] },
    { result: "lootjs:yellow_croaker",              candidates: ["kaleidoscope_chinesefood:yellow_croaker"] },

    // ===== 蛋类 =====
    { result: "lootjs:egg",                         candidates: ["minecraft:egg"] },
    { result: "lootjs:cooked_egg",                  candidates: ['vanillacookbook:cooked_egg', 'mynethersdelight:boiled_egg', 'kaleidoscope_cookery:fried_egg'] },

    // === 4. 谷物、豆类与基础食材 (Grains, Beans & Ingredients) ===
    { result: "lootjs:barley",                      candidates: ["farm_and_charm:barley"] },
    { result: "lootjs:barley_seeds",                candidates: ["farm_and_charm:barley_seeds"] },
    { result: "lootjs:bread",                       candidates: ["minecraft:bread"] },
    { result: "lootjs:cookie",                      candidates: ["minecraft:cookie"] },
    { result: "lootjs:raw_cheese_wheel",            candidates: ['casualnessdelight:raw_cheese_wheel', 'brewinandchewin:unripe_flaxen_cheese_wheel', 'trailandtales_delight:curd_block'] },
    { result: "lootjs:cheese_block",                candidates: ['casualnessdelight:cheese_wheel', 'brewinandchewin:flaxen_cheese_wheel', 'vintagedelight:cheese_wheel', 'trailandtales_delight:cheese_wheel', 'kitchenkarrot:cheese_wheel'] },
    { result: "lootjs:cheese_slice",                candidates: ['casualnessdelight:cheese_wheel_slice', 'brewinandchewin:flaxen_cheese_wedge', 'vintagedelight:cheese_slice', 'trailandtales_delight:cheese_slice', 'kitchenkarrot:cheese_slice'] },
    { result: "lootjs:cocoabeans",                  candidates: ["minecraft:cocoa_beans"] },
    { result: "lootjs:raw_coffee_beans",            candidates: ['youkaishomecoming:green_coffee_bean', "youkaisfeasts:green_coffee_bean", "rusticdelight:coffee_beans", "bakeries:raw_coffee_bean"] },
    { result: "lootjs:roasted_coffee_beans",        candidates: ['youkaishomecoming:coffee_beans', "youkaisfeasts:coffee_beans", "rusticdelight:roasted_coffee_beans", "bakeries:coffee_bean"] },
    { result: "lootjs:coffee_powder",               candidates: ['youkaishomecoming:coffee_powder', "youkaisfeasts:coffee_powder", "bakeries:ground_coffee"] },
    { result: "lootjs:cooked_rice",                 candidates: ["kaleidoscope_cookery:cooked_rice", "farmersdelight:cooked_rice"] },
    { result: "lootjs:flour",                       candidates: ["kaleidoscope_cookery:flour", "farm_and_charm:flour", "create:wheat_flour", "bakeries:whole_wheat_flour"] },
    { result: "lootjs:honey",                       candidates: ["minecraft:honey_bottle"] },
    
    { result: "lootjs:oat",                         candidates: ["farm_and_charm:oat", "vintagedelight:oat"] },
    { result: "lootjs:oat_seeds",                   candidates: ["farm_and_charm:oat_seeds", "vintagedelight:oat_seeds"] },
    { result: "lootjs:peanut",                      candidates: ["vintagedelight:peanut"] },
    { result: "lootjs:pods",                        candidates: ["youkaishomecoming:pods", "youkaisfeasts:pods"] },
    { result: "lootjs:redbean",                     candidates: ["youkaishomecoming:redbean", "youkaisfeasts:redbean"] },
    { result: "lootjs:rice",                        candidates: ["kaleidoscope_cookery:rice", "farmersdelight:rice"] },
    { result: "lootjs:salt",                        candidates: ["kaleidoscope_chinesefood:salt", "voidlessframework:salt", "bakeries:salt", "vintagedelight:salt_dust"] },
    { result: "lootjs:soybean",                     candidates: ["youkaishomecoming:soybean", "youkaisfeasts:soybean"] },
    { result: "lootjs:soybean_seeds",               candidates: ["youkaishomecoming:soybean_seeds", "youkaisfeasts:soybean_seeds"] }, 
    { result: "lootjs:sugar",                       candidates: ["minecraft:sugar"] },
    { result: "lootjs:sweet_potato",                candidates: ["veggiesdelight:sweet_potato"] },
    { result: "lootjs:wheat",                       candidates: ["minecraft:wheat"] },
    { result: "lootjs:wheat_seeds",                 candidates: ["minecraft:wheat_seeds"] },

    // === 5. 林业与经济作物 (Forestry & Textiles) ===
    { result: "lootjs:acorn",                       candidates: ["seeddelight:acorn"] },
    { result: "lootjs:cotton",                      candidates: ["rusticdelight:cotton_boll"] },
    { result: "lootjs:cotton_seeds",                candidates: ["rusticdelight:cotton_seeds"] },
    { result: "lootjs:pinecone",                    candidates: ["seeddelight:pinecone"] },
    { result: "lootjs:sugar_cane",                  candidates: ["seeddelight:sugar_cane"] },
    { result: "lootjs:tea_seeds",                   candidates: ["youkaishomecoming:tea_seeds", "youkaisfeasts:tea_seeds"] },
    { result: "lootjs:flax",                         candidates: ["supplementaries:flax"] },
    { result: "lootjs:flax_seeds",                   candidates: ["supplementaries:flax_seeds"] },

    // === 6. 矿物与金属材料 (Minerals & Materials) ===
    { result: "lootjs:amethyst",                    candidates: ["minecraft:amethyst_shard"] },
    { result: "lootjs:coal",                        candidates: ["minecraft:coal"] },
    { result: "lootjs:copper_ingot",                candidates: ["minecraft:copper_ingot"] },
    { result: "lootjs:diamond",                     candidates: ["minecraft:diamond"] },
    { result: "lootjs:emerald",                     candidates: ["minecraft:emerald"] },
    { result: "lootjs:gold_ingot",                  candidates: ["minecraft:gold_ingot"] },
    { result: "lootjs:iron_ingot",                  candidates: ["minecraft:iron_ingot"] },
    { result: "lootjs:lapis",                       candidates: ["minecraft:lapis_lazuli"] },
    { result: "lootjs:netherite",                   candidates: ["minecraft:netherite_ingot"] },
    { result: "lootjs:quartz",                      candidates: ["minecraft:quartz"] },
    { result: "lootjs:raw_copper",                  candidates: ["minecraft:raw_copper"] },
    { result: "lootjs:raw_gold",                    candidates: ["minecraft:raw_gold"] },
    { result: "lootjs:raw_iron",                    candidates: ["minecraft:raw_iron"] },
    { result: "lootjs:raw_zinc",                    candidates: ["create:raw_zinc"] },
    { result: "lootjs:redstone",                    candidates: ["minecraft:redstone"] },
    { result: "lootjs:zinc_ingot",                  candidates: ["create:zinc_ingot"] },
    { result: "lootjs:gunpowder",                   candidates: ["minecraft:gunpowder"] },

    // === 7. 工具类 (Tools) ===
    { result: "lootjs:small_iron_knife",            candidates: ["farmersdelight:iron_knife", "kitchenkarrot:knife", "bakery:bread_knife", "bakeries:bread_knife"] },
    { result: "lootjs:plate",                       candidates: ['youkaishomecoming:saucer', 'kitchenkarrot:plate_item']},   

];

// ==================== 2. 逻辑处理 ====================
if ( config.createDuplicateItemSwapRecipe === true) {
    createDuplicateItemSwapRecipe (DUPLICATE_ITEMS_CONFIG) 
}
if ( config.createDuplicateItemPreviewLootTable === true) {
    createDuplicateItemPreviewLootTable (DUPLICATE_ITEMS_CONFIG);
}

let crateAndBagRegistry = [
// === 1. 蔬菜箱 (Vegetable Crates & Bags) ===
    { name: "beetroot_block",               ids: ["farmersdelight:beetroot_crate", "farm_and_charm:beetroot_bag"] },
    { name: "beetroot_seeds_block",         ids: ["cratedelight:beetroot_seeds_bag"] },
    { name: "bell_pepper_green_block",      ids: ["rusticdelight:bell_pepper_green_crate"] },
    { name: "bell_pepper_red_block",        ids: ["rusticdelight:bell_pepper_red_crate"] },
    { name: "bell_pepper_yellow_block",     ids: ["rusticdelight:bell_pepper_yellow_crate", "veggiesdelight:bellpepper_crate"] },
    { name: "cabbage_block",                ids: ["farmersdelight:cabbage_crate"] },
    { name: "carrot_block",                 ids: ["farmersdelight:carrot_crate", "farm_and_charm:carrot_bag"] },
    { name: "chinese_cabbage_block",        ids: ["dumplings_delight:chinese_cabbage_crate"] },
    { name: "corn_block",                   ids: ["farm_and_charm:corn_bag", "corn_delight:corn_crate", "culturaldelights:corn_cob_crate"] },
    { name: "corn_seeds_block",             ids: ["corn_delight:corn_kernel_bag"] },
    { name: "cucumber_block",               ids: ["youkaisfeasts:cucumber_crate", "vintagedelight:cucumber_crate", "culturaldelights:cucumber_crate"] },
    { name: "eggplant_block",               ids: ["dumplings_delight:eggplant_crate", "culturaldelights:eggplant_crate"] },
    { name: "fennel_block",                 ids: ["dumplings_delight:fennel_crate"] },
    { name: "garlic_chive_block",           ids: ["dumplings_delight:garlic_chive_crate"] },
    { name: "garlic_block",                 ids: ["dumplings_delight:garlic_crate", "veggiesdelight:garlic_crate"] },
    { name: "greenonion_block",             ids: ["dumplings_delight:greenonion_crate"] },
    { name: "dried_kelp_block",             ids: ["minecraft:dried_kelp_block"] },
    { name: "lettuce_block",                ids: ["farm_and_charm:lettuce_bag"] },
    { name: "brown_mushroom_block",         ids: ["cratedelight:brown_mushroom_crate"] },
    { name: "red_mushroom_block",           ids: ["cratedelight:red_mushroom_crate"] },
    { name: "onion_block",                  ids: ["farmersdelight:onion_crate", "farm_and_charm:onion_bag"] },
    { name: "pepper_block",                 ids: ["muffins_thaidelight:pepper_crate", "vintagedelight:ghost_pepper_crate"] },
    { name: "poisonous_potato_block",       ids: ["cratedelight:poisonous_potato_crate"] },
    { name: "potato_block",                 ids: ["farmersdelight:potato_crate", "farm_and_charm:potato_bag"] },
    { name: "pumpkin_slice_block",          ids: ["cratedelight:pumpkin_slice_crate"] },
    { name: "pumpkin_seeds_block",          ids: ["cratedelight:pumpkin_seeds_bag"] },
    { name: "tomato_block",                 ids: ["farmersdelight:tomato_crate", "farm_and_charm:tomato_bag"] },
    { name: "white_eggplant_block",         ids: ["culturaldelights:white_eggplant_crate"] },
    { name: "golden_carrot_block",          ids: ["cratedelight:golden_carrot_crate"] },
    { name: "broccoli_block",               ids: ["veggiesdelight:broccoli_crate"] },
    { name: "cauliflower_block",            ids: ["veggiesdelight:cauliflower_crate"] },
    { name: "turnip_block",                 ids: ["veggiesdelight:turnip_crate"] },
    { name: "zucchini_block",               ids: ["veggiesdelight:zucchini_crate"] },
    { name: "chickpea_block",               ids: ["ramadandelight:chickpea_bag"] },
    { name: "parsley_block",                ids: ["ramadandelight:parsley_bag"] },
    { name: "mint_leaves_block",            ids: ["neapolitan:mint_basket"] },
    { name: "adzuki_beans_block",           ids: ["neapolitan:adzuki_crate", "neapolitan:adzuki_bag"] },
    { name: "vanilla_pods_block",           ids: ["neapolitan:vanilla_pod_block"] },

    // === 2. 水果箱 (Fruit Crates) ===
    { name: "banana_block",                 ids: ["neapolitan:banana_crate"] },
    { name: "date_block",                   ids: ["ramadandelight:date_crate"] },
    { name: "apple_block",                  ids: ["cratedelight:apple_crate", "fruitsdelight:apple_crate"] },
    { name: "avocado_block",                ids: ["culturaldelights:avocado_crate"] },
    { name: "bayberry_block",               ids: ["fruitsdelight:bayberry_crate"] },
    { name: "berry_block",                  ids: ["cratedelight:berry_crate"] },
    { name: "black_grape_block",            ids: ["youkaisfeasts:black_grape_crate", "youkaishomecoming:black_grape_crate"] },
    { name: "blueberry_block",              ids: ["fruitsdelight:blueberry_crate"] },
    { name: "cherry_block",                 ids: ["seeddelight:cherry_crate"] },
    { name: "cranberry_block",              ids: ["fruitsdelight:cranberry_crate"] },
    { name: "fig_block",                    ids: ["fruitsdelight:fig_crate"] },
    { name: "gearo_berry_block",            ids: ["vintagedelight:gearo_berry_bag"] },
    { name: "glowberry_block",              ids: ["cratedelight:glowberry_crate"] },
    { name: "hawberry_block",               ids: ["fruitsdelight:hawberry_crate"] },
    { name: "kiwi_block",                   ids: ["fruitsdelight:kiwi_crate"] },
    { name: "lemon_block",                  ids: ["fruitsdelight:lemon_crate"] },
    { name: "lime_block",                   ids: ["muffins_thaidelight:lime_crate"] },
    { name: "lychee_block",                 ids: ["fruitsdelight:lychee_crate"] },
    { name: "mango_block",                  ids: ["fruitsdelight:mango_crate"] },
    { name: "mangosteen_block",             ids: ["fruitsdelight:mangosteen_crate"] },
    { name: "melon_seeds_block",            ids: ["cratedelight:melon_seeds_bag"] },
    { name: "orange_block",                 ids: ["fruitsdelight:orange_crate"] },
    { name: "papaya_block",                 ids: ["muffins_thaidelight:papaya_crate"] },
    { name: "peach_block",                  ids: ["fruitsdelight:peach_crate"] },
    { name: "pear_block",                   ids: ["fruitsdelight:pear_crate"] },
    { name: "persimmon_block",              ids: ["fruitsdelight:persimmon_crate"] },
    { name: "pineapple_block",              ids: ["fruitsdelight:pineapple_crate", "pineapple_delight:pineapple_crate"] },
    { name: "red_grape_block",              ids: ["youkaisfeasts:red_grape_crate", "youkaishomecoming:red_grape_crate"] },
    { name: "rosehip_block",                ids: ["seeddelight:rosehip_crate"] },
    { name: "strawberry_block",             ids: ["farm_and_charm:strawberry_bag", "neapolitan:strawberry_basket"] },
    { name: "white_grape_block",            ids: ["youkaisfeasts:white_grape_crate", "youkaishomecoming:white_grape_crate"] },
    { name: "golden_apple_block",           ids: ["cratedelight:golden_apple_crate"] },

    // === 3. 肉类与海鲜箱 (Meat & Seafood Crates) ===
    { name: "cod_block",                    ids: ["cratedelight:cod_crate"] },
    { name: "egg_block",                    ids: ["cratedelight:egg_crate"] },
    { name: "salmon_block",                 ids: ["cratedelight:salmon_crate"] },
    { name: "pufferfish_block",             ids: ["cratedelight:pufferfish_crate"] },
    { name: "tropical_fish_block",          ids: ["cratedelight:tropical_fish_crate"] },
    { name: "crab_block",                   ids: ["crabbersdelight:crab_barrel"] },
    { name: "clawster_block",               ids: ["crabbersdelight:clawster_barrel"] },
    { name: "shrimp_block",                 ids: ["crabbersdelight:shrimp_barrel"] },
    // { name: "calamari_block",               ids: ["crabbersdelight:squid_barrel"] },
    { name: "clam_block",                   ids: ["crabbersdelight:clam_barrel"] },

    // === 4. 谷物、豆类与基础食物袋 (Grains, Beans & Food Bags) ===
    { name: "bread_block",                  ids: ["cratedelight:bread_bag"] },
    { name: "cocoabeans_block",             ids: ["cratedelight:cocoabeans_bag"] },
    { name: "raw_coffee_beans_block",       ids: ["rusticdelight:coffee_beans_bag"] },
    { name: "roasted_coffee_beans_block",   ids: ["youkaishomecoming:coffee_bean_bag", "rusticdelight:roasted_coffee_beans_bag"] },
    { name: "cookie_block",                 ids: ["cratedelight:cookie_bag"] },
    { name: "flour_block",                  ids: ["farm_and_charm:flour_bag", "bakeries:wheat_flour_bag"] },
    { name: "honey_block",                  ids: ["minecraft:honey_block"] },
    { name: "oat_block",                    ids: ["farm_and_charm:oat_ball", "vintagedelight:oat_bag"] }, // 注：原名本身为bale/ball，已按要求保留
    { name: "peanut_block",                 ids: ["vintagedelight:peanut_crate"] },
    { name: "pod_block",                    ids: ["youkaisfeasts:pod_crate", "youkaishomecoming:pod_crate"] },
    { name: "redbean_block",                ids: ["youkaisfeasts:redbean_bag", "youkaishomecoming:redbean_bag"] },
    { name: "rice_block",                   ids: ["farmersdelight:rice_bag"] },
    { name: "rice_panicle_block",           ids: ["farmersdelight:rice_panicle_bag", "farmersdelight:rice_bale"] },
    { name: "soybean_block",                ids: ["youkaisfeasts:soybean_bag", "youkaishomecoming:soybean_bag"] },
    { name: "sugar_block",                  ids: ["cratedelight:sugar_bag"] },
    { name: "sweet_potato_block",           ids: ["veggiesdelight:sweet_potato_crate"] },
    { name: "wheat_block",                  ids: ["minecraft:hay_block"] },
    { name: "wheat_seeds_block",            ids: ["cratedelight:wheat_seeds_bag"] },
 

    // === 5. 林业与经济作物袋 (Forestry & Textile Bags) ===
    { name: "acorn_block",                  ids: ["seeddelight:acorn_bag"] },
    { name: "cotton_block",                 ids: ["rusticdelight:cotton_boll_crate"] },
    { name: "pinecone_block",               ids: ["seeddelight:pinecone_bag"] },
    { name: "flax_block",                   ids: ["supplementaries:flax_block"] },


    // === 6. 矿物与金属箱 (Minerals & Materials Crates & Blocks) ===
    { name: "amethyst_block",               ids: ["minecraft:amethyst_block"] },
    { name: "coal_block",                   ids: ["minecraft:coal_block"] },
    { name: "copper_block",                 ids: ["minecraft:copper_block"] },
    { name: "diamond_block",                ids: ["minecraft:diamond_block"] },
    { name: "emerald_block",                ids: ["minecraft:emerald_block"] },
    { name: "gold_block",                   ids: ["minecraft:gold_block"] },
    { name: "iron_block",                   ids: ["minecraft:iron_block"] },
    { name: "lapis_block",                  ids: ["minecraft:lapis_block"] },
    { name: "netherite_block",              ids: ["minecraft:netherite_block"] },
    { name: "quartz_block",                 ids: ["minecraft:quartz_block"] },
    { name: "raw_copper_block",             ids: ["minecraft:raw_copper_block"] },
    { name: "raw_gold_block",               ids: ["minecraft:raw_gold_block"] },
    { name: "raw_iron_block",               ids: ["minecraft:raw_iron_block"] },
    { name: "raw_zinc_block",               ids: ["create:raw_zinc_block"] },
    { name: "redstone_block",               ids: ["minecraft:redstone_block"] },
    { name: "zinc_block",                   ids: ["create:zinc_block"] },

    { name: "gunpowder_block",              ids: ["cratedelight:gunpowder_bag"] },


    { name: "rope",                         ids: ['farmersdelight:rope', 'supplementaries:rope', 'farm_and_charm:rope', 'beautify:rope'] },

];

// 映射转换并直接覆盖原数组名
crateAndBagRegistry = crateAndBagRegistry.map(item => ({
    result: `lootjs:${item.name}`, 
            candidates: item.ids
}));

// if (config.createDuplicateItemPreviewLootTable === true) {
//     createDuplicateItemPreviewLootTable(crateAndBagRegistry);
// }

const mergeItem = DUPLICATE_ITEMS_CONFIG.concat(crateAndBagRegistry);

const configMap = {};
if (typeof mergeItem !== 'undefined' && Array.isArray(mergeItem)) {
    mergeItem.forEach(entry => { configMap[entry.result] = entry.candidates; });
}