const modifiersToRemove = [
    "farmersdelight:add_loot_abandoned_mineshaft",
    // "farmersdelight:add_loot_bastion_hoglin_stable",
    // "farmersdelight:add_loot_bastion_treasure",
    "farmersdelight:add_loot_end_city_treasure",
    "farmersdelight:add_loot_pillager_outpost",
    "farmersdelight:add_loot_ruined_portal",
    "farmersdelight:add_loot_shipwreck_supply",
    "farmersdelight:add_loot_simple_dungeon",
    "farmersdelight:add_loot_village_butcher",
    "farmersdelight:add_loot_village_desert_house",
    "farmersdelight:add_loot_village_plains_house",
    "farmersdelight:add_loot_village_savanna_house",
    "farmersdelight:add_loot_village_snowy_house",
    "farmersdelight:add_loot_village_taiga_house",
    // "farmersdelight:add_onion_to_illagers",
    // "farmersdelight:add_onion_to_zombies",
    // "farmersdelight:scavenging_feather",
    // "farmersdelight:scavenging_ham_from_hoglin",
    // "farmersdelight:scavenging_ham_from_pig",
    // "farmersdelight:scavenging_leather",
    // "farmersdelight:scavenging_pumpkin",
    // "farmersdelight:scavenging_rabbit_hide",
    // "farmersdelight:scavenging_shulker_shell",
    // "farmersdelight:scavenging_smoked_ham_from_hoglin",
    // "farmersdelight:scavenging_smoked_ham_from_pig",
    // "farmersdelight:scavenging_string",
    // "farmersdelight:slicing_apple_pie",
    // "farmersdelight:slicing_cake",
    // "farmersdelight:slicing_candle_cake",
    // "farmersdelight:slicing_chocolate_pie",
    // "farmersdelight:slicing_pumpkin_pie",
    // "farmersdelight:slicing_sweet_berry_cheesecake",
    // "farmersdelight:straw_from_grass",
    // "farmersdelight:straw_from_mature_rice",
    // "farmersdelight:straw_from_mature_wheat",
    // "farmersdelight:straw_from_sandy_shrub",
    // "farmersdelight:straw_from_tall_grass",

    "corn_delight:shipwreck_loot",
    "corn_delight:village_house",

    // "dumplings_delight:add_calamari_glow_squid",
    // "dumplings_delight:add_calamari_squid",
    "dumplings_delight:add_loot_abandoned_mineshaft",
    "dumplings_delight:add_loot_pillager_outpost",
    "dumplings_delight:add_loot_shipwreck_supply",
    "dumplings_delight:add_loot_simple_dungeon",
    "dumplings_delight:add_loot_village_desert_house",
    "dumplings_delight:add_loot_village_plains_house",
    "dumplings_delight:add_loot_village_savanna_house",
    "dumplings_delight:add_loot_village_snowy_house",
    "dumplings_delight:add_loot_village_taiga_house",

    // "vintagedelight:add_loot_bastion_hoglin_stable",
    "vintagedelight:add_loot_ruined_portal",
    "vintagedelight:add_loot_village_desert_house",
    "vintagedelight:add_loot_village_plains_house",
    "vintagedelight:add_loot_village_savanna_house",
    "vintagedelight:add_loot_village_snowy_house",
    "vintagedelight:add_loot_village_taiga_house",
    // "vintagedelight:straw_from_mature_oat",

    "muffins_thaidelight:add_loot_village_taiga_house",
    "muffins_thaidelight:add_loot_village_snowy_house",
    "muffins_thaidelight:add_loot_village_savanna_house",
    "muffins_thaidelight:add_loot_village_plains_house",
    "muffins_thaidelight:add_loot_village_desert_house",
    "muffins_thaidelight:add_loot_pillager_outpost",
    "muffins_thaidelight:add_loot_abandoned_mineshaft",

    "chalk:abandoned_mineshaft_chest_chalks",
    "chalk:bonus_chest_chalks",
    "chalk:desert_pyramid_chest_chalks",
    "chalk:simple_dungeon_chest_chalks",
    "chalk:village_chest_chalks",

    "rationcraft:igloo_i",
    "rationcraft:mineshaft_i",
    "rationcraft:stronghold_i",
    "rationcraft:village_butcher_i",
    "rationcraft:village_fish_i",
    
    "kitchenkarrot:pillager_pie_from_mansion_loot_modifier",
    "kitchenkarrot:pillager_pie_from_outpost_loot_modifier",
    "kitchenkarrot:pillager_pie_from_pillager_loot_modifier",

    "vanillacookbook:add_loot_abandoned_mineshaft",
    // "vanillacookbook:add_loot_bastion_treasure",
    "vanillacookbook:add_loot_end_city_treasure",
    // "vanillacookbook:add_loot_golden_hoe",
    // "vanillacookbook:add_loot_nether",
    "vanillacookbook:add_loot_simple_dungeon",
    // "vanillacookbook:add_loot_spawn_bonus_chest",
    "vanillacookbook:add_loot_village_desert_house",
    "vanillacookbook:add_loot_village_plains_house",
    "vanillacookbook:add_loot_village_savanna_house",
    "vanillacookbook:add_loot_village_snowy_house",
    "vanillacookbook:add_loot_village_taiga_house",
    "vanillacookbook:add_loot_woodland_mansion",

    "travelersbackpack:abandoned_mineshaft_inject_gold_tier_upgrade",
    "travelersbackpack:abandoned_mineshaft_inject_iron_tier_upgrade",
    "travelersbackpack:abandoned_mineshaft_inject_standard",
    // "travelersbackpack:bastion_treasure_inject_gold_tier_upgrade",
    // "travelersbackpack:bastion_treasure_inject_iron_tier_upgrade",
    // "travelersbackpack:bat",
    "travelersbackpack:desert_pyramid_inject_gold_tier_upgrade",
    "travelersbackpack:desert_pyramid_inject_iron_tier_upgrade",
    "travelersbackpack:desert_pyramid_inject_standard",
    // "travelersbackpack:end_city_treasure_inject_diamond_tier_upgrade",
    // "travelersbackpack:end_city_treasure_inject_gold_tier_upgrade",
    // "travelersbackpack:hay",
    // "travelersbackpack:iron_golem",
    // "travelersbackpack:nether_bridge_inject_gold_tier_upgrade",
    // "travelersbackpack:nether_bridge_inject_iron_tier_upgrade",
    "travelersbackpack:shipwreck_treasure_inject_gold_tier_upgrade",
    "travelersbackpack:shipwreck_treasure_inject_iron_tier_upgrade",
    "travelersbackpack:simple_dungeon_inject_iron_tier_upgrade",
    "travelersbackpack:simple_dungeon_inject_standard",
    "travelersbackpack:woodland_mansion_inject_gold_tier_upgrade",
    "travelersbackpack:woodland_mansion_inject_iron_tier_upgrade",

    "immersive_armors:armor_modifier_serializer",

    "immersiveenchanting:abandoned_mineshaft_ancient_books",
    "immersiveenchanting:all_tables_ancient_books",
    // "immersiveenchanting:ancient_city_ancient_books",
    // "immersiveenchanting:bastion_bridge_ancient_books",
    // "immersiveenchanting:bastion_other_ancient_books",
    // "immersiveenchanting:bastion_treasure_ancient_books",
    "immersiveenchanting:buried_treasure_ancient_books",
    "immersiveenchanting:desert_pyramid_ancient_books",
    "immersiveenchanting:end_city_ancient_books",
    "immersiveenchanting:igloo_chest_ancient_books",
    "immersiveenchanting:jungle_temple_ancient_books",
    // "immersiveenchanting:nether_bridge_ancient_books",
    "immersiveenchanting:pillager_outpost_ancient_books",
    // "immersiveenchanting:remove_enchanted_books",
    "immersiveenchanting:ruined_portal_ancient_books",
    "immersiveenchanting:shipwreck_treasure_ancient_books",
    "immersiveenchanting:simple_dungeon_ancient_books",
    "immersiveenchanting:stronghold_corridor_ancient_books",
    "immersiveenchanting:stronghold_library_ancient_books",
    "immersiveenchanting:trial_chambers_reward_ancient_books",
    "immersiveenchanting:underwater_ruin_big_ancient_books",
    "immersiveenchanting:underwater_ruin_small_ancient_books",
    "immersiveenchanting:woodland_mansion_ancient_books",


    "touhou_little_maid:abandoned_mineshaft",
    // "touhou_little_maid:ancient_city",
    // "touhou_little_maid:bastion_treasure",
    // "touhou_little_maid:chest_power_point",
    "touhou_little_maid:desert_pyramid",
    "touhou_little_maid:end_city_treasure",
    // "touhou_little_maid:fishing_power_point",
    "touhou_little_maid:jungle_temple",
    // "touhou_little_maid:maid_buried_treasure",
    // "touhou_little_maid:nether_bridge",
    "touhou_little_maid:pillager_outpost_gift",
    // "touhou_little_maid:power_point",
    "touhou_little_maid:simple_dungeon",
    // "touhou_little_maid:spawn_bonus_chest",
    "touhou_little_maid:stronghold_corridor",
    "touhou_little_maid:stronghold_library",
    "touhou_little_maid:stronghold_library_board_state",
    "touhou_little_maid:village_cartographer",
    "touhou_little_maid:village_temple",
    "touhou_little_maid:woodland_mansion_bauble",
    "touhou_little_maid:woodland_mansion_gift",

    "miners_delight:add_loot_abandoned_mineshaft",

    "veggiesdelight:add_loot_abandoned_mineshaft",
    "veggiesdelight:add_loot_pillager_outpost",
    "veggiesdelight:add_loot_shipwreck_supply",
    "veggiesdelight:add_loot_simple_dungeon",
    "veggiesdelight:add_loot_village_desert_house",
    "veggiesdelight:add_loot_village_plains_house",
    "veggiesdelight:add_loot_village_savanna_house",
    "veggiesdelight:add_loot_village_snowy_house",
    "veggiesdelight:add_loot_village_taiga_house",
    // "veggiesdelight:slicing_beetroot_brownie_tray",
    // "veggiesdelight:slicing_carrot_cake",
    // "veggiesdelight:slicing_sweet_potato_pie",
    // "veggiesdelight:slicing_vegan_pizza",
    // "veggiesdelight:slicing_zucchini_quiche",

    "ramadandelight:add_loot_abandoned_mineshaft",
    "ramadandelight:add_loot_desert_pyramid",
    "ramadandelight:add_loot_shipwreck_supply",
    "ramadandelight:add_loot_village_desert_house",
    "ramadandelight:add_loot_village_plains_house",
    "ramadandelight:add_loot_village_savanna_house",
    "ramadandelight:add_loot_village_snowy_house",
    "ramadandelight:add_loot_village_taiga_house",
    // "ramadandelight:slicing_quiche",

    // "rusticdelight:calamari_from_glow_squid",
    // "rusticdelight:calamari_from_squid",
    "rusticdelight:coffee_beans_from_jungle_temple",
    "rusticdelight:cotton_seeds_from_abandoned_mineshaft",
    "rusticdelight:cotton_seeds_from_shipwreck_supply",
    "rusticdelight:cotton_seeds_from_village_savanna",
    "rusticdelight:cotton_seeds_from_village_snowy",
    "rusticdelight:cotton_seeds_from_village_taiga",
    "rusticdelight:dark_bell_pepper_seeds_from_jungle_temple",
    "rusticdelight:pale_bell_pepper_seeds_from_jungle_temple"

];

// 执行批量移除
removeGlobalModifiersBatch(modifiersToRemove);