modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"


[[dependencies.${mod_id}]]
modId = "polymorph"
type = "required"
versionRange = "[0.0.0,)"
ordering = "NONE"
side = "BOTH"


[[dependencies.${mod_id}]]
modId = "ramadandelight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "rationcraft"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "repurposed_structures"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "revampedvillages"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "roadweaver"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "rusticdelight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "supplementaries"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "touhou_little_maid"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "trailandtales_delight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "travelersbackpack"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "trek"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "vanillacookbook"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "veggiesdelight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "vintagedelight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "better_loot_zibura"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "brewery"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "brewinandchewin"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "chalk"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "corn_delight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ctov"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "dumplings_delight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "explorify"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "farmersdelight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "immersive_armors"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "immersiveenchanting"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kaisyn"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kattersstructures"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kitchenkarrot"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "miners_delight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "muffins_thaidelight"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neapolitan"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "nova_cherry_village"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "nova_structures"
type = "optional"
versionRange = "[0.0.0,)"
ordering = "AFTER"
side = "BOTH"