modLoader="lowcodefml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
  modId="betterloot_zibura"
  version="0.4.0"
  displayName="betterloot_zibura"
  authors="zibura"
  description='''Put vanilla and mod items where they belong, and make loot tables more diverse, rewarding, and reasonable.'''

[[dependencies.betterloot-zibura-neoforge-1.21.1]]
    modId="neoforge"
    mandatory=false
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.betterloot-zibura-neoforge-1.21.1]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"

